### ISSUE TITLE
[Questionnaire] Skip logic dropdown gets hidden inside Multiple Choice Responses component 

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#1022]
Version: 0.9.2 (build 2424)

1. Create a questionnaire
2. Add several steps
3. Add a multiple choice step
4. Add a response to the multiple choice step
5. Click on Skip logic dropdown to select a step

Obtained:
The dropdown gets hidden inside the Responses component and it enables it to be scrollable 

![screen shot 2017-05-26 at 6 47 58 pm](https://cloud.githubusercontent.com/assets/9214460/26513800/e6904048-4243-11e7-84ba-383e1fcf69ad.png)

http://g.recordit.co/7nKK5vhKVY.gif

**Comment by asterite** [comment]
https://github.com/Dogfalo/materialize/issues/2827

**Comment by manumoreira** [comment]
Seems to be a problem with materialize, @bcardiff it worth to explore a workaround for this?

**Comment by bcardiff** [comment]
For dropdown that uses a limited amount of options (with no autocomple behavior) I would suggest using a native `<select><option>` elements. The loss will be the style of the options/elements itself.
