### ISSUE TITLE
Validate Steps flow.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1043]
Found in version: 51b2425

Now some invalid steps flow can be created.

Probably we should have the following "rules":
-any flag step can be added if there is no flags added previously.
-`completed` can be placed after a `partial` flag.
-any other steps sequence should be invalid.

Reproduce steps:
Create a Questionnaire Foo.
Add some steps.
Add a `Partial` flag.
Add an `Ineligible` step after the `Partial` flag. 
Create a Survey.
Select the Questionnaire `Foo`.
Complete the wizard.
Start the Survey.
As respondent answer the Survey until the `Ineligible` step.

Obtained:
The respondent is marked as Completed.

Expected:
The respondent should be marked as `Partial`.
An `Ineligible` step placed after a `Partial` step doesn't make sense. This behavior should be validated.

**Comment by manumoreira** [comment]
Won't fix
