### ISSUE TITLE
Group tables for multiple choice and add switch buttons

### ISSUE THREAD

**Issue by nditada** [instedd/surveda#1053]
<img width="692" alt="screen shot 2017-06-06 at 6 13 48 pm" src="https://user-images.githubusercontent.com/1359189/26839652-f6a73998-4ae3-11e7-8b96-ccbdbc053b7a.png">

**Comment by nditada** [comment]
Already implemented in the sidebar for now.

**Comment by manumoreira** [comment]
This applies to an old UI
