### ISSUE TITLE
Confirmation email is sent to Spam folder.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1066]
Environment: https://surveda-zambia.org/

Version: 0.9.4

Reproduce steps:
Navigate to the landing page.
Press the Sign up button.
Fill the fields.
Submit the form.
Go to the email Inbox folder.
Go to the email Spam folder.

Obtained:
Confirmation email is sent to Spam folder.

Expected:
Confirmation email should be sent to the Inbox folder.

**Comment by waj** [comment]
This is not an issue in the code, but probably a misconfiguration on each environment
