### ISSUE TITLE
Add description field to questionnaire

### ISSUE THREAD

**Issue by adam704a** [instedd/surveda#1068]
It would be nice to have an open-ended “description” field that I could use to remind myself what different questionnaires are. For example, we just switched over from a questionnaire that includes “data charges may apply” in SMS to a questionnaire that says “no cost to reply.” So we have 2 questionnaires that are 99% similar, with this one difference. The only place to track that difference (i.e., how is quex A different than quex B) is in a doc outside of the tool OR in my head (not a great idea!)

**Comment by mmuller** [comment]
Working properly in version 672562a
