### ISSUE TITLE
[Questionnaire] Onboarding is displayed when readers open a shared proyect's questionnaire

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#1107]
Version: 0.10.0-dev-8e75560 (build 2581)

Precondition:
There is a user that already has a project `Foo` with a questionnaire set up

1. As user owner of project `Foo` go to 'Collaborators'
2. Add a collaborator in reader mode
3. As 'Reader' user open project `Foo` and go to 'Questionnaires'
4. Open a questionnaire

Obtained:
The questionnaire opens on a Onboarding state, its steps appear only after the user clicks on "Understood".

![screen shot 2017-06-23 at 11 56 13 am](https://user-images.githubusercontent.com/9214460/27488877-fab2c86c-580e-11e7-8124-77c5e740ca01.png)

**Comment by mmuller** [comment]
It doesn't depend on the questionnaire's content. It only happens if the collaborator never created a step.

**Comment by mmuller** [comment]
Working properly in version ca3d196
