### ISSUE TITLE
Add date in Incentive file.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1113]
Feature requested by Charles Lau.

 

> As someone who manages the survey, I want to have a "date" field in the Incentive File, so I can easily distribute incentives.

> Right now, we need to provide incentives to respondents 2 x per week. If we don't have a date field, then I have to manually merge to determine which cases still require incentives. If I had a date field, I could just sort by date, and then cut and paste telephone numbers from the last X days (e.g, 3 days). This would make incentive distributions easy for users, and would reduce the likelihood that we would mistakenly not provide incentives to people.

**Comment by manumoreira** [comment]
Add the date in which the respondent has completed the survey

**Comment by mmuller** [comment]
Working properly in version 3e05578
