### ISSUE TITLE
Add time for voice call in Survey Results file.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1114]
Feature requested by Charles Lau.

> Add a variable for "Number of Seconds" spent on IVR call. This applies to IVR only.
As someone who writes reports summarizing survey progress, I need to report the length of the IVR survey. This is a standard component of methodological reports, and can only be done now with complicated merging with the Dispositions/Interactions file.

**Comment by manumoreira** [comment]
[Currently](https://github.com/instedd/surveda/commit/63fd132713b5486d588c63840754e951d214758d) the total_call_time column includes this information
--
