### ISSUE TITLE
[Questionnaire] Skip logic can't be changed to new flags

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#1119]
What Happened: 
1) I created a new questionnaire
2) At the end I added a couple flags, and dragged them into location in the questionnaire that I wanted
3)  I then went back to previously created steps, to try and set the skip criteria to go to those flag steps. 
4) When I selected the drop down list for old options, _not all the steps were present as options_. 
5) If I created a new categorical option, I _could_ see all the steps.

at surveda.instedd.org  on Version: 0.9.5 (build 2505)

**Comment by steesdale** [comment]
![untitled](https://user-images.githubusercontent.com/3987608/27935020-2ea67a1a-626e-11e7-88d8-1de849c74c32.gif)

**Comment by manumoreira** [comment]
This is working ok in version  [63fd132](https://github.com/instedd/surveda/commit/63fd132713b5486d588c63840754e951d214758d)
