### ISSUE TITLE
Inconsistencies in Exported CSV Reports

### ISSUE THREAD

**Issue by edjez** [instedd/surveda#1121]
Finding the following in interactions report from a pretest:
Note the mode=IVR when the channel is SMPP and interactions look like SMS (i.e. 3 prompts)

Hopefully this is in the 'rendering' of the CSV and not an issue in the capture of the info

![image](https://user-images.githubusercontent.com/1182549/28438909-a2022ffe-6d54-11e7-9a2c-c482b0f89ed8.png)

**Comment by manumoreira** [comment]
We've checked this in several interactions files in Malawi and Morocco and we didn't find these inconsistencies.
