### ISSUE TITLE
The size of the initial batches is too low

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1125]
Reported by Charles:
"When cutoffs are assigned, sample release is slow. Nico and I have had several skype discussions about this. I still believe the size of Surveda’s initial batches is too low. Another example: In Zambia Zamtel full-scale, we had cutoffs of ~750 interviews (with 6 strata). But Surveda only released 8500 cases initially! This can’t be right; I think there is something wrong with Surveda’s calculations here. Note that I am NOT proposing we adjust the overarching model (i.e., make it less conservative); I am suggesting that the way the model is implemented in the tool is not right. This is a topic for research and discussion."

**Comment by nditada** [comment]
This was my response to Charles: 
When Surveda does not have a cutoff target or quotas to estimate the size of the queue, the default value is 1000. It's likely that 10 additional numbers failed quickly and the rest are just pending for retries.

**Comment by nditada** [comment]
The problem with this is the following:

1. During the first phase of scheduling, Surveda schedules 100 calls per minute.
2. After a few completes, the "composed" success rate starts taking into account the actual success rate. 
3. The actual success rate is calculated as completes/(completes + failed)
4. We don't have any initial fails in the beginning as we decided that we can't trust MNO errors as permanent, so failed = 0 until all retries are done with respondents.
5. per (3) and (4), the actual success rate is 1, so even if it's weighted by the completion %, it still makes the current success rate too big.

The only solution we can think of right now is to add the "actives" to the denominator. This will make the problem swing to the other side, i.e. the actual success rate will be too low, as we are basically assuming all actives will be faileds.

**Comment by nditada** [comment]
From Adam 
> Charles and I discussed. Let's hold off on doing anything until we have a few more large scale surveys under our belt.

https://mobilesurveys.freshdesk.com/a/tickets/60
