### ISSUE TITLE
Improve Responses CSV.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1136]
Reported by Charles:
"Survey Response File: Move Dispositions and Date fields to be the second and third columns in the file.
Any data analyst will need to filter responses by Disposition Code. The current set up requires users to cut and paste the Disposition column or do other burdensome things. This is a small edit that can save users time."

**Comment by manumoreira** [comment]
After sample_file and before the first quex step add disposition	total_call_time	total_sent_sms	total_received_sms (and any other column that's always present)

**Comment by mmuller** [comment]
@manumoreira It is working properly in version 3e05578 but `total_call_time` `total_sent_sms` `total_received_sms` are placed before `sample_file`
