### ISSUE TITLE
Improve Responses CSV.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1139]
Reported by Charles:
"Survey Response File: Include three more fields:
- Mode of first question answered
- Mode of last question answered
- Variable name where mode switched (if modes are different.) If modes are same, then this variable is blank.
In a mixed mode survey, it is standard practice to compare people who answer in SMS versus IVR. This is a project requirement, as well. Right now, it’s burdensome to do this calculation. This would also allow analysts to easily see whether people switched modes. In the pre-test, RTI data analysts collective spent about 20-30 hours (and lots of money) merging “mode” from the Interactions file (and confirming the merge was correct)."

**Comment by manumoreira** [comment]
The retries count is good enough for now https://github.com/instedd/surveda/issues/1516
