### ISSUE TITLE
"Poison" SMS message is retried indefinitely, blocking surveys for some respondents

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#1150]
The following message:

"1/3 Cipatso copelekedwa ndi apple yokulilako pangòno, nthoci, manga, gwawa kapena theka ya kapu ya zipatso zophikidwa kapena kudulidwa/dulidwa."

Fails most of the time to go through Zamtel SMSCs when sent as an MT from Nuntium to Zamtel subscribers.

At some point in the interaction between Nuntium and the SMSC, an unhandled exception is raised which ends up causing the survey to effectively halt for respondents reaching that question for that language.

Removing 3 characters from this message fixes the issue, so it seems there's differences between how Nuntium and the Zamtel channel compute message length (this is just a wild guess based on observed behavior and not an appropriately validated hypothesis). 

Once we go through full scale in Zambia, we should run a Nuntium console and try to reproduce the issue there.

**Comment by manumoreira** [comment]
This never happened again after Zambia, the only solution I see for this is checking this sort of scenarios (try SMS with limit values of character) before going live.
