### ISSUE TITLE
Allow "stop" to be sent as opt-out keyword at any time during a survey

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#1151]
While monitoring the Zambia servers to make sure that everything was running smoothly, I noticed some people sent “Stop” to opt-out halfway through the survey and many days after their last interaction (for example, see: 5ae1323c-05d1-fa3b-412e-5d84de6024e6 and c14a5128-0d07-5b3a-dc0a-ad4df84148d8).

We should probably consider this case and handle it gracefully.

**Comment by manumoreira** [comment]
This works as described in version  [63fd132](https://github.com/instedd/surveda/commit/63fd132713b5486d588c63840754e951d214758d)
