### ISSUE TITLE
Wrong questionnaire was rendered in Survey's overview.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1153]
Original comment by Charles Lau:
 
"1. I logged into Surveda ZNDC
2. I created a new survey (test survey) https://surveda-zambia.org/projects/2/surveys/195/edit
3. In that survey, I selected "Zambia NCD Mobile Phone Survey - 8 languages"
4. I clicked out of that new test survey
5. I opened the main Full Scale survey
6. At that point, the "Zambia NCD Mobile Phone Survey - 8 languages" showed up.
7. Is it possible that somehow the other quex label got piped over temporarily? Would be surprised if this was a coincidence."

Reference: https://mobilesurveys.freshdesk.com/helpdesk/tickets/46

**Comment by manumoreira** [comment]
It seems lijke the quex name was not updating correctly, now it works ok for version [63fd132](https://github.com/instedd/surveda/commit/63fd132713b5486d588c63840754e951d214758d)
