### ISSUE TITLE
"Ask" instead of "Surveda" in account confirmation email

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#1161]
When I signed up to surveda-morocco.org (Version 0.10.2), I got the confirmation email below. Notice the blue button which reads "Confirm my Ask account" while it should read "Confirm my Surveda account".

<img width="613" alt="screen shot 2017-09-06 at 1 56 00 pm" src="https://user-images.githubusercontent.com/651693/30124533-d73aaebc-930b-11e7-929d-2138d277889c.png">

**Comment by mmuller** [comment]
This issue can be reproduced in surveda.instedd.org (0.10.2) too.

**Comment by manumoreira** [comment]
As this is managed by guiso now, this issue doesn't make sense.
This is how the email confirmation looks like
<img width="534" alt="Screen Shot 2019-11-13 at 13 49 01" src="https://user-images.githubusercontent.com/31930782/68785089-64e80680-061c-11ea-8326-d94eaf3d7cf9.png">
