### ISSUE TITLE
[Survey] Improve the label 'Respondents contacted' in the overview.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1162]
In #1128 @nditada said:
> (...) the issue is in the use of the word "Contacted" in that part of the UI, we are not using it in alignment with the definition for dispositions. In fact, I think that word has been there since before we even agreed on what dispositions we would have and which names they would take.
We'll adjust this in the next round of modifications to that screen.

In my opinion we should replace the word `Respondents` too. In that count we are including `Failed`, this state doesn't refer to people already contacted. Before `Contacted` is still a `phone number`. I mean a `phone number` becomes `Respondent` after `Contacted` disposition.
I think that the label should be something like `Phone numbers already used`.

**Comment by manumoreira** [comment]
@nditada Enrolled respondents sounds good?

**Comment by nditada** [comment]
@manumoreira nop, enrolled presupposes a voluntary action. What is the definition of the number that would go below that label?

**Comment by manumoreira** [comment]
@nditada The number of respondents attempted or (total respondents - uncontacted)

**Comment by nditada** [comment]
"Attempted respondents"?

**Comment by manumoreira** [comment]
A little bit long, but correct. Will share with RTI/CDC and get their confirmation

**Comment by manumoreira** [comment]
CDC Confirmed to change the label to "Attempted Respondents"

**Comment by manumoreira** [comment]
<img width="1678" alt="Screen Shot 2020-01-28 at 12 32 26" src="https://user-images.githubusercontent.com/31930782/73278739-cacf3d80-41ca-11ea-969d-f79970dcf849.png">

**Comment by mmuller** [comment]
Working properly in version 672562a
