### ISSUE TITLE
After creating a questionnaire from survey the user is not redirected back to survey

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#118]
Version: 0.2.0-prod
1. Create a survey
2. Create a questionnaire in step 'Select a questionnaire'
3. Save created questionnaire

Obtained:
User is redirected to section 'Questionnaire' and not back to the survey

**Comment by juanboca** [comment]
Since we will have Autosave for questionnaires, the SAVE button is no longer there, and thus the redirect doesn't exist anymore.

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/206254031/preview

**Comment by nditada** [comment]
@mmuller Can you confirm we can close this?

**Comment by mmuller** [comment]
Working properly in version be9eb68.
The user is not redirected after creating a survey. 
Questionnaires have `autosave` now.
