### ISSUE TITLE
Show start time in Survey's Overview.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1267]
Version 6a459a3

When a Survey is running its start time must be shown in the Overview.

![image](https://user-images.githubusercontent.com/518152/36919515-5f598c80-1e3c-11e8-9872-f6a68499f092.png)

Current version:

![image](https://user-images.githubusercontent.com/518152/36919573-8f846308-1e3c-11e8-8734-707cfb429d35.png)

**Comment by waj** [comment]
The start time must be also displayed in the survey cards
