### ISSUE TITLE
Results file: variable names should not have spaces.

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1401]
it creates import annoyances to other software. This applies to both variable names and the ones that surveda assigns.
<img width="1161" alt="gxfk_qaha9mm4kzjw9lyz9sc2bh8hied6w" src="https://user-images.githubusercontent.com/31930782/40626128-f17ca69e-628c-11e8-958e-6109060eaee5.png">

**Comment by mmuller** [comment]
It is not working properly in version 6146d81. Variables created by the user include spaces.

**Comment by mmuller** [comment]
Working properly in version f48c221
