### ISSUE TITLE
Some languages can't be found when uploading the translation CSV

### ISSUE THREAD

**Issue by juanboca** [instedd/surveda#1423]
When `Old French (842-ca. 1400)` is one of the selected languages, if the user downloads the content for translation, adds some translations into this language and uploads it again, the server returns 422 when trying to save.

One example: The thank you message ends up having "null" as one of the language keys.
`"thank_you_message" => %{
"en" => %{"sms" => "Thanks for completing!"}, 
"es" => %{"sms" => "Gracias por completar!"}, "null" => %{"ivr" => %{"audio_source" => "tts", "text" => ""}, "mobileweb" => "", "sms" => "Merci!"}}}`

This happens because the language.js library is used to translate the code of a language into the name of it for the CSV download, and then when the CSV is uploaded it translates the name back to the code. For this language, the library returns null, and this ends up being used in the csv without checking.

First, the conversion from code->name and name->code should always return the original value
Second, if the nameToCode function doesn't find the language, that column should be ignored and a notification should be shown to the user

**Comment by mmuller** [comment]
Working properly in version 6146d81
