### ISSUE TITLE
Autosave time is displayed incorrectly

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1443]
When a questionnaire is saved, the time displayed "jumps" randomly around ~10 minutes from the real value. For example it's common to make a change and right after the changes are saved the banner shows something like: "Successfully saved 7 minutes ago".

**Comment by lmatayoshi** [comment]
Related with #958

**Comment by pmallol** [comment]
Ok in Version: 0.21.0-dev-5d1bf9e (build 3283)
