### ISSUE TITLE
Show upload progress when a questionnaire is being uploaded

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1444]
Specially when the questionnaire being imported includes audios it takes some time to upload. Let's show some kind of progress indicator.

@jkicillof could you provide a design for this?

**Comment by jkicillof** [comment]
https://invis.io/2TMXFAVHVQM#/333305013_Z_Index_-_Upload

**Comment by pmallol** [comment]
Ok in Version: 0.21.0-dev-5d1bf9e (build 3283)
