### ISSUE TITLE
Several respondents get an 'Unauthorized' when accessing their Mobile web survey

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#1445]
Version 0.16.2 (build 3189)

There could be a problem with Google URL shortener (a service that will be [discontinued in March 30, 2019](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html)). Apparently the survey links attached in the SMS are opened before the user can open the survey in a browser.

Also, when disabling Google URL shortener, the survey URL can be misinterpreted by the phone carrier and arrive to the user in a way that cannot be properly opened in the browser.
For example, the following url 
`https://surveda-stg.instedd.org/mobile_survey/9677144?token=5c5e36edfff7`
is received by sms as 
`https://surveda-stg.instedd.org/mobile`¿`survey/9677144?token=5c5e36edfff7`

Preconditions:
There is a Questionnaire `Foo`.
`Foo` has enabled only the mode `Mobile web`.
There's a QST (server) channel configured through nuntium

1. Create a Survey
2. Select the Questionnaire `Foo`.
3. Select the `Web mobile` mode
4. Add several respondents (~10)
5. Complete the wizard
6. Launch the Survey
7. In Nuntium, check the AO messages
8. Try to open the mobile web surveys linked in the SMS messages 
(e.g. There's a web survey here `https://goo.gl/DBs4Ra`)

Expected:
The user can access the survey and answer it via web

Obtained:
The user cannot answer the survey, the following message appears instead:
> You are not authorized to participate in the survey

**Comment by waj** [comment]
There are three different problems here so I'm splitting this issue:
  * https://github.com/instedd/surveda/issues/1520
  * https://github.com/instedd/surveda/issues/1521
  * https://github.com/instedd/surveda/issues/1522
