### ISSUE TITLE
Questionnaire CSV cannot be downladed via Firefox

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#1446]
Version: 0.16.2 (build 3189)
Firefox: 63.0.1 (64-bit)

Preconditions:
There is a Questionnaire `Foo`

1. Open Questionnaire `Foo`
2. Click on the three dots button next to its title
3. Select option `Download contents as CSV`

Obtained:
Nothing is downloaded

Expected:
A CSV file with the questionnaire content is downloaded through the browser

**Comment by mmuller** [comment]
Working properly in version 6146d81
