### ISSUE TITLE
Alert to project admins when a channel is down

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1449]
Before each broker loop, check the channels in Nuntium or Verboice and send an alert to the project administrator when the channel is down. Make sure the alert is not sent on every cycle, until the channel is back online.

https://projects.invisionapp.com/share/3U8BARPXJ#/screens/285073159

**Comment by waj** [comment]
[ ] Extend Verboice API to include channel status
  [ ] Channel Status Server
    [ ] Check every X minutes the status of each active channel
    [ ] Send emails when a channel goes down
    [ ] Interrupt survey processing when a channel is down

**Comment by lmatayoshi** [comment]
Two more screens were added:

When a channel which is currently used by a running survey is down, an orange rounded span should be displayed. Additional information should be display in brackets whenever is available.
https://projects.invisionapp.com/d/main#/console/8374235/279907804/preview

In case some channels down, survey cards of running surveys that are currently using those channels should display the message: "Channel/s {name_1, name_2 ...} down for {X minutes/hours/days}". In case that many channels are down, the longest down time should be displayed.
https://projects.invisionapp.com/d/main#/console/8374235/180693793/preview
Information displayed in the survey card should match info displayed in the survey overview.

**Comment by lmatayoshi** [comment]
In addition to sending emails to project admins when channels are down, surveys with down channels should stop starting new respondents

**Comment by lmatayoshi** [comment]
known issue: At this time, emails are being sent only to project owners (which are the channel owners) instead of project admins (users invited to the project as admins). This can be fixed by modifying the `handle_info(:poll, state)` function in `channel_status_server`

**Comment by mmuller** [comment]
Alert is not sent to the project administrator when a Verboice channel is disabled (version 6146d81)

**Comment by mmuller** [comment]
Working properly in version f48c221
