### ISSUE TITLE
Error in "Total call time" when expired calls are involved

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1452]
In https://surveda-morocco.org/projects/3/surveys/210 some respondents have huge amount of "Total call time" >4000 mins. 
After reviewing some cases I've found a relation between this large call time and "expired" calls in Verboice, as if the call time calculation has started when a call was expired and ended only after the next successful call. (eg: 7fc88ba9522d, 44c61817b053)
This is the verboice instance https://verboice-inwi.surveda-morocco.org

**Comment by mmuller** [comment]
Working properly in version 672562a
