### ISSUE TITLE
What License does Surveda use?

### ISSUE THREAD

**Issue by leebrian** [instedd/surveda#1469]
I manage the open.cdc.gov web site and got a pull request yesterday, https://github.com/CDCgov/opencdc/pull/38, to add Surveda to our open technology portal as a useful public health code project.

However, I'm not sure what open source license y'all use. I don't see a LICENSE file or a GitHub property describing the license.

What license is Surveda developed and published under?

**Comment by nditada** [comment]
GPLv3.
