### ISSUE TITLE
[Quotas] When set to 0 surveda doesn't reject those cases

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1470]
In this survey at Malawi RTI has set some quotas to 0 but lots of respondents on those quotas received the complete survey.
https://surveda-mw.org/projects/2/surveys/215/settings

**Comment by waj** [comment]
Copied from @devduarte's PR:

> A new radio button was added for the survey cutoff step to set a default configuration. User should not be allowed to launch a survey when the configured cutoff or quotas buckets are zero and its radio button is checked accordingly. When the default configuration is checked in the step, both quota buckets and cutoff should empty and user should be allowed to launch the survey.
> 
> -If the user blanks the cutoff input, then a cutoff with a zero value is dispatched. Lower bound validation of cutoff was changed to cover this case.
> 
> An error message is displayed if there are no quotas to configure.
> 
> Sum of quotas is being calculated for both SurveyForm and SurveyWizardCutoffStep components, I think it will better to do this calculation in a reducer and use it from there.

**Comment by mmuller** [comment]
Working properly in version f48c221
