### ISSUE TITLE
Navigation alert when setting quotas

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1479]
![image](https://user-images.githubusercontent.com/22697/61741708-dcd9aa80-ad67-11e9-86a4-c5d0fa43d59d.png)

### Steps to reproduce
1 - Go edit a Survey
2 - Scroll down to `Setup cutoff rules`
3 - Select `Quotas for completes`
4 - Confirm the popup
5 - You usually get an alert from the browser stating that there's data being saved

**Comment by mmuller** [comment]
Working properly in version f48c221
