### ISSUE TITLE
Internal server error in channels Settings

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1481]
**Found in version:**
6146d81

**Preconditions:**
Create a channel in Nuntium.

**Steps to reproduce:**
Create a channel `Foo` in Nuntium. 
Reload the Channels listing.
Navigate to the Channels settings.
Observe the browser's console.

**Obtained:**
An internal server error is thrown.
GET https://nuntium-stg.instedd.org/channels_ui/0-22-client?access_token=G5V1rAFtc9NuMTKJcNUyJsWEIbgDSjP9Wf3Kiv7ooww&account=mmuller%40manas.com.ar 500 (Internal Server Error)

Related to #1480

**Comment by waj** [comment]
This is an issue with the embeddable Channels UI in Nuntium. I just created this issue: https://github.com/instedd/nuntium/issues/45
