### ISSUE TITLE
Error in modes column in the respodents file

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1482]
RTI found some cases in which the modes column is not showing the Phone call,  SMS mode when it should. 
In this survey https://surveda-mw.org/projects/2/surveys/216/respondents we have these two cases 
```
+-----------+---------------
| survey_id | hashed_number 
+-----------+---------------
|       216 | 93a730b7e42e  | 
|       216 | be1d758124be  | 
+-----------+---------------
```
That only have phone call in the respondents file attached but in the db it shows ivr, sms
[TNM_FULL_SCALE__2-respondents_2019-07-23-22-09-42 (1).txt](https://github.com/instedd/surveda/files/3443656/TNM_FULL_SCALE__2-respondents_2019-07-23-22-09-42.1.txt)
```
mysql> select mode from respondents where hashed_number = '93a730b7e42e';
+---------------+
| mode          |
+---------------+
| ["ivr","sms"] |
+---------------+
mysql> select mode from respondents where hashed_number = 'be1d758124be';
+---------------+
| mode          |
+---------------+
| ["ivr","sms"] |
+---------------+
```

**Comment by matiasgarciaisaia** [comment]
From the data we have, we called the respondent, they started answering the survey, and then the call was dropped in the middle of the survey.

Respondent was queued for a retry (again on IVR), but then we received an SMS from the respondent _before_ retrying them. Surveda assumed the respondent was replying to the survey via SMS and "implicitly" switched to SMS.

Relevant internal IDs:
`ATVId_f0a3dbc49b9073f46903067f9b7acd19`
ATs `33283`, `33285`, `33286`
AOs `439898`, `439899`, `439900`, `439901`

**Comment by matiasgarciaisaia** [comment]
Surveda should ignore respondents' contacts through a mode that's not the current active one.

**Comment by mmuller** [comment]
Working properly in version 2de3bab
