### ISSUE TITLE
Intercom button appears twice in channels settings

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1483]
Version 6146d81

Steps to reproduce:
Add a Channel
Navigate to the Channel `settings`
Observe the `update` button

Obtained:
The Intercom button appears twice in channels settings

![image](https://user-images.githubusercontent.com/518152/62071259-85798580-b212-11e9-9339-c1fd172db40c.png)

![image](https://user-images.githubusercontent.com/518152/62071337-af32ac80-b212-11e9-9f0e-7a99d2a276a4.png)

**Comment by waj** [comment]
This issue must be fixed in Verboice and Nuntium. I just created these issues:

https://github.com/instedd/nuntium/issues/44
https://github.com/instedd/verboice/issues/833

**Comment by mmuller** [comment]
Working properly in version f48c221
