### ISSUE TITLE
Succes rate and queue size cockpit

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1488]
Add the "success rate" and "queue size" sections of the cockpit to the survey status page

https://projects.invisionapp.com/share/2TMXFAVHVQM#/screens/241966468

@jkicillof already implemented the UI components. Let's try to integrate them into the project.
https://github.com/instedd/surveda-d3-components

**Comment by mmuller** [comment]
**Found in version:** 4f50b9c

- [ ] The  total count of **missing** is wrong. This number should be: **number of `needed` - number of pending respondents** (respondents that could be marked as completed).

- [ ] Numbers rounding is not correct, ie. now we are showing `0,019` as `0,020`. 

**Screenshot:**

![image](https://user-images.githubusercontent.com/518152/65350800-ee4eff80-dbbc-11e9-882a-4e95040aa609.png)

**Comment by mmuller** [comment]
When the survey is starting and the respondents are still queued the `Estimated success rate` should be `0.0028`.
(1 / 0.0028 = 358)

![image](https://user-images.githubusercontent.com/518152/66131502-ea15df80-e5c9-11e9-9abb-6b81bae640ca.png)

**Comment by mmuller** [comment]
Sometimes the multiplier is not correctly rounded.

In this case, the following screenshot shows that the multiplier is rounded down so the number of needed respondents won't be enough to complete the survey:

![image](https://user-images.githubusercontent.com/518152/66135607-98bd1e80-e5d0-11e9-8bf6-a42afb1d142f.png)

The number of needed should be `380` (20 * 19).
