### ISSUE TITLE
Add a column to the respondents CSV with the order of the sections

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1492]
When a questionnaire has randomized sections, the order in which the sections is actually executed for a respondent is valuable information. Let's add a `section_order` column for these cases containing the name of the sections in the order they were (or going to be) executed for that respondent (separated by commas).

NOTE: the order of the sections is currently stored only during the respondent execution. After a respondent session is finished that info is discarded (the `session` column is set to `NULL`). So a new column must be added to the `respondents` table to persist this information. I suggest a `section_order` column containing a JSON with the index of the sections, just like it's currently stored within the session (for example: `[3, 0, 2, 1]`). When the CSV is generated these indexes will be converted to the section names.

**Comment by mmuller** [comment]
Working properly in version 8bc45df
