### ISSUE TITLE
Stop survey in background

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1517]
Currently the `stop` action for surveys is executed in a process mostly synchronous with the action within the surveys controller. For big surveys this is time consuming and it often fails with a timeout or out of memory error.

Let's add a `stopping` state for the survey while the stop actions are executed in background. Once the actions are terminated the state must be set to `terminated`.

**Comment by mmuller** [comment]
Working properly in version d7ff690

**Comment by mmuller** [comment]
I could verify that after stopping the survey:

- the dispositions didn't change
- the survey is marked as `canceled`
- the stopped survey doesn't trigger more calls
- the queued calls are marked as canceled in Verboice

**Comment by bcardiff** [comment]
Known Issue

* if the canceling of a queued call fails that might leave the survey as _canceling..._ forever. The failure of the cancellation is not handled. Note: that a restart of the server is allowed and the cancellation will continue.

**Comment by anaPerezGhiglia** [comment]
When a channel is deleted (`Channel.delete(channel)`) all surveys that are running at the moment with that channel are terminated and all their respondents are cancelled. This action is still synchronous so it could trigger the same issue addressed here
Check `Survey.cancel_respondents(survey)`
