### ISSUE TITLE
Do not log requeue of expired calls in the interactions file

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1519]
Currently every time an enqueued call expires a new row is added to the interactions file. On large surveys with limited IVR bandwidth this results in a high percentage of the lines of that CSV to be just re-enqueue of the same respondent calls many times giving little value for the analysis.

Let's remove those lines from the CSV

@manumoreira could you provide an example of the lines to remove?

**Comment by manumoreira** [comment]
<img width="873" alt="Screen Shot 2019-09-30 at 16 30 23" src="https://user-images.githubusercontent.com/31930782/65909835-cf602280-e39f-11e9-891f-502b0f55297a.png">
The line that needs to be removed is "Call expired, will be retried in the last schedule window"

**Comment by mmuller** [comment]
Working properly in version d7ff690
