### ISSUE TITLE
Remove underscore from mobile web URL

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1520]
Currently the URL generated and sent via SMS to each respondent has an underscore. It was noticed that it causes issues with some carriers/devices: https://github.com/instedd/surveda/issues/1445

Let's remove that character from the URL replacing `mobile_survey` by `mobile`. The resulting URL would be: `https://<server>/mobile/<respondent_id>?token=<token>`

**Comment by mmuller** [comment]
Working properly in version d7ff690
