### ISSUE TITLE
Remove validation of multiple respondents sharing a mobile survey URL

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1521]
This is causing some trouble: https://github.com/instedd/surveda/issues/1445

Given that a URL cannot be used twice even from the same device, I think we could remove that validation.

**Comment by nditada** [comment]
Just making sure we don't loose the conversation that happened over Slack in Sep 20. We basically agreed that we could: 
1- Send the URL as always, and not try to block initial access to avoid #1445 
2- When the user starts the survey, send a token over SMS (maybe another link?)
3- The authorization cookie for that device is only setup at that point.

**Comment by nditada** [comment]
Discuss with RTI/CDC the side-effects: double SMS cost, increased survey initiation friction

**Comment by mmuller** [comment]
Working properly in version f18d5cc
