### ISSUE TITLE
Optimize questionnaire export

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1525]
Currently when a questionnaire is exported the process generates the ZIP file in memory. This is unacceptable for large questionnaires with hundreds of audio files.

Instead, the export should stream the audios from the DB into the ZIP file generated and streamed on the fly over the HTTP connection.

For this a different library should be used that works with an Elixir `Stream`. If found this one that seems to fit quite well: `https://hex.pm/packages/zstream`.

**Comment by mmuller** [comment]
When trying to export ~10 MB questionnaires the download process is stopped and a message reads `Failed - Network error` (version 1984618).

**Comment by mmuller** [comment]
Working properly in version a98ec31
