### ISSUE TITLE
Retries histogram

### ISSUE THREAD

**Issue by waj** [instedd/surveda#1526]
https://projects.invisionapp.com/share/2TMXFAVHVQM#/screens/241966468

Let's start with the "gray" portion of the chart. That means, it will display enqueued respondents and respondents waiting for the next retry.

**Comment by bcardiff** [comment]
* When the survey is finished, the chart should not be show
* 1 chart should be shown per each mode sequence (note that the header will be different: it can start with voice and fallback to sms, or the opposite)
* Two respondents using different questionnaires, but same modes will appear in the same

**Comment by bcardiff** [comment]
Split in #1547 coding of the last time window between last retry and drop-off of respondent for sms

**Comment by bcardiff** [comment]
* Add link that triggers a full-page reload to show the histogram. Append query string parameter for that

**Comment by mmuller** [comment]
Component added correctly in version 0392aec
