### ISSUE TITLE
Emails `from` address should not be hardcoded

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#1549]
Surveda currently hardcodes it's `From:` header for emails to `noreply@instedd.org`.

Since we manage different installations of Surveda, we should be able to use different domains, at least.

There are two possibilities:

1) Send the emails from `noreply@{current_host}` (ie, `noreply@surveda.instedd.org`, `noreply@surveda-lk.org`)

2) Send the emails from an address configured in the settings/environment (ie, add a `SMTP_FROM_ADDRESS` with a value like `noreply@surveda-lk.org`)

**Comment by matiasgarciaisaia** [comment]
**Note**: once this is deployed, we should update the policies of the Surveda SMTP users in IAM so they can't send emails from `noreply@instedd.org` anymore.

**Comment by matiasgarciaisaia** [comment]
We should also probably let the sender name to be customised. It's currently hardcoded to `InSTEDD Surveda`, which doesn't give any idea on which instance the e-mail is coming from.

**Comment by bcardiff** [comment]
Ideally, the following format should be used: 

```
SMTP_FROM_ADDRESS="InSTEDD Surveda <noreply@instedd.org>"
```

**Comment by mmuller** [comment]
Working properly in version 1984618
