### ISSUE TITLE
Log cancelling to cancelled change in activity log

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1555]
In the activity log the cancelling, cancelled is not logged. it is logged as instantaneous

Ref: #1517

**Comment by mmuller** [comment]
Version 3ffaf2e

When cancelling a survey the user name is not logged: 

![image](https://user-images.githubusercontent.com/518152/78812468-d8aaf700-79a1-11ea-8f23-55690dfd3257.png)

**Comment by bcardiff** [comment]
@mmuller as long as there is a request for cancellation logged on behalf the user, that message should be fine. For now the background processes run as a system user and not the user that originated the request.

**Comment by mmuller** [comment]
@bcardiff since the surveys can be called by different collaborators, the current behavior could be confusing.
As the project owner, I would like to know which contributor canceled the survey.

**Comment by bcardiff** [comment]
But the cancelling request should be logged with the user that requested it. If that is missing we can fix that.

**Comment by mmuller** [comment]
Yes, the user name is missing in the activity log.

**Comment by mmuller** [comment]
Replace `Cancelling` with `Stopped`.
