### ISSUE TITLE
[Retries histogram] When the sample is small the scale has decimals

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1581]
![image](https://user-images.githubusercontent.com/518152/70172436-6d79ad00-16af-11ea-84cc-5fd142c2f785.png)

**Comment by matiasgarciaisaia** [comment]
Let's take a look at the component to check if it's easy to avoid showing non-integer steps in the scale (both the line and the legend).

If hiding the line is difficult, let's just avoid showing non-integer labels.

**Comment by matiasgarciaisaia** [comment]
Running some tests, it looks like the issue only happens when `0`, `1` or `2` are the maximum amount of respondents for any given column of the chart.

**Comment by jkicillof** [comment]
I've added a filter to exclude non integer ticks and also changed the formatter used on those

**Comment by aeatencio** [comment]
Will be solved in https://github.com/instedd/surveda-d3-components/releases/tag/v1.0.15
Already solved in instedd/surveda-d3-components@71a3c2b and instedd/surveda-d3-components@30621e5

**Comment by mmuller** [comment]
Working properly in version 9a760ad
