### ISSUE TITLE
Cancelling surveys can't have a 0 exit code

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#1582]
The code that [cancels surveys in background](https://github.com/instedd/surveda/blob/b21f7ff9fc730abe45a7c68512f36bc09718d70a/web/static/js/components/surveys/SurveyStatus.jsx#L147-L151) assumes there can be a Cancelling survey with a status code 0 - which can't actually happen.

We should check that and delete the extra code.

See #1517

**Comment by mmuller** [comment]
Working properly in version 672562a
