### ISSUE TITLE
[Retries histogram] Add tooltip to make more comprehensible the number of enqueued calls

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1584]
![image](https://user-images.githubusercontent.com/518152/70279472-5319ff00-1795-11ea-9759-7fe82dbaf518.png)

Related to #1581

**Comment by jkicillof** [comment]
The current version of retries histogram includes a tooltip

**Comment by aeatencio** [comment]
Will be solved in https://github.com/instedd/surveda-d3-components/releases/tag/v1.0.15
Already solved in https://github.com/instedd/surveda-d3-components/commit/7a996e19f8d327ac3f90a149426f0ffaa1098078

**Comment by mmuller** [comment]
Working properly in version 9a760ad
