### ISSUE TITLE
Retries count is failing in surveda-ec

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1589]
We have several cases in this survey https://surveda-ec.org/projects/3/surveys/24 with 3 in the ivr_attempts column but are still in queued or interim partial dispositions.
As the total amount of tries for the survey is 3 and the mode is `IVR only` after 3 retries there shouldn't be any respondent flagged as queued or interim partials with 3 retries.

[results&interactions.zip](https://github.com/instedd/surveda/files/3941412/results.interactions.zip)

**Comment by manumoreira** [comment]
Surveda is currently counting internal contact attempts. For Surveda an attempt is requesting the channel to make the contact. But from the surveda's user perspective attempt means when the channel really tries to contact the respondent.
For SMS and Mobile Web there's no difference between surveda attempt and channel attempt, or there is no way to make a difference.

In verboice, if there are lots of calls queued in the channel it might happen that many of them will be expired and re-queued another time, while surveda will have counted all calls as attempted.
/This can be easily reproduced by queueing ~1k calls for a small contact time range in a channel with limit 1. This will generate a bunch of expired calls in verboice that surveda will have counted as a successful attempt./

To get the desired behaviour we need to count every time a call is started and/or failed on verboice. The challenge is that we can get many callbacks to surveda from every verboice call, to avoid mistakes counting many times the callbacks from the same call we should save at surveda a set of call_ids from which we have received the first callback Answer except the expired and queued calls. So if we have the case of a call that was Answer and then Fail we will only count it once.

**Comment by matiasgarciaisaia** [comment]
Related to #1516

**Comment by mmuller** [comment]
Working properly in version aaa80a6
