### ISSUE TITLE
Retry stats errors make the whole app crash

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#1594]
- [x] Handle errors when RetryStats receives a filter with any required field `nil`
- [x] Add required field validations in DB
- [x] Add a new `ivr_active` field in RetryStat to avoid polysemy in `retry_time`
- [x] Add a FK between RetryStats and Respondents
- [x] Use the RetryStat changeset for DB insert and updates
- [x] Use `try/rescue` and / or a different process for RetryStats persistence
- [ ] Fix and improve tests

**Comment by mmuller** [comment]
Working properly in version 672562a
