### ISSUE TITLE
Add start date for 'scheduled' surveys

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1601]
Add start date for **scheduled** surveys in the:
 
- [ ] Survey's overview. 
- [ ] Surveys listing.

Besides that we need to improve the information displayed in the Surveys listing. 
 - [ ] ~Replace `Scheduled at 9 AM (America - Buenos Aires)` with `Next contact 7 days`.~
 - [x] Unify the "survey scheduled for" message in the survey card and overview. See #1855.

![image](https://user-images.githubusercontent.com/518152/71278447-6a7cee80-2336-11ea-8f72-6a64e4ebd34c.png)

![image](https://user-images.githubusercontent.com/518152/71278462-736dc000-2336-11ea-9c4f-ce802cbd63e5.png)

**Comment by manumoreira** [comment]
The "Scheduled for"messages were unified in #1855 but we are still not including the start and end dates when start_date is different from `window_start_date`
We might want to add a new message in the survey overview (it will not fit in the survey card) that specify start and end dates.
A simple option would be a message similar to the one that is shown when the survey is closed (defined by surveyRanDescription) in black font below the "Scheduled for" message.

**Comment by aeatencio** [comment]
First part of the message:

1. The survey was launched but it didn't entered in its first active window -> `Didn't start yet`
2. The survey alredy entered in its first active window -> `Started on <first_window_started_at>`

Second part of the message:

1. The survey has an `end_date` -> ` and will end on <last_window_end_at>`
2. The survey doesn't has an `end_date` -> no second part of the message.

**Comment by mmuller** [comment]
Now in version 7235dc9 the `end_date` is showing 1 day before the `end_date`

![image](https://user-images.githubusercontent.com/518152/114453221-b436bb80-9baf-11eb-9b40-12a464598d5c.png)

![image](https://user-images.githubusercontent.com/518152/114453262-bef15080-9baf-11eb-80b4-ff29e1ce2fbf.png)

**Comment by aeatencio** [comment]
> Now in version 7235dc9 the end_date is showing 1 day before the end_date

It will be fixed for #1859. Please let's track this there 🙏

**Comment by mmuller** [comment]
Awesome! Working properly in version 7235dc9
