### ISSUE TITLE
[Survey] Add clarification of localtime of the selected timezone

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1604]
When selecting `Etc - GMT-5` the surveys uses `Etc - GMT+5`.

At 4pm (GMT-5) I got the following result:

![image (18)](https://user-images.githubusercontent.com/518152/71588700-37d6b100-2b01-11ea-8282-98d922d01f74.png)

![image (17)](https://user-images.githubusercontent.com/518152/71588701-37d6b100-2b01-11ea-9389-31e981edc22e.png)

Besides that some Capital cities (ie. Quito) are not included as options. We should improve the options listing.

**Comment by bcardiff** [comment]
We will add a caption next to the autocomplete with the current local time of the selected timezone.

**Comment by bcardiff** [comment]
The Etc - GMT-5 timezone corresponds to GMT+5  and vice versa. 
Since there the list of timezone have some missing locations the user is likelly to fall into these options.
The clarification of localtime of the selected timezone should mitigate the confusion.

**Comment by mmuller** [comment]
Working properly in version 672562a
