### ISSUE TITLE
Record STOP MO and marked them as Partial/Breakoff/Refused

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1607]
When a respondent sends STOP MO we need to stop sending SMS or calls. 
Now all these cases are flagged as refused, but it's only correct for the respondents that have no answers, when a respondent has one or more answers we should use a different flag.
When the respondent has answered one or more questions but didn't reach a partial
 flag it should be flagged as Breakoff
When a respondent has reached a partial flag and then sent STOP we should flag it with a new disposition called STOPPED.
![STOP op2](https://user-images.githubusercontent.com/31930782/71744902-67f6ba80-2e47-11ea-8990-05747ea5de8e.png)

**Comment by bcardiff** [comment]
The current decision is to:

  * Add respondent column `user_stopped : Bool`
  * Exportación `user_stopped` in respondents file (before dynamic columns)
  * When on SMS a `STOP` is receive, set `user_stopped = true` at move to the next final state
    * Contacted -> Refused
    * Started -> Breakoff
    * InterimPartial -> Partial
  * Double-check the respondent is no longer contacted (even if there are available retries)

**Comment by manumoreira** [comment]
![dispoDiagramStop](https://user-images.githubusercontent.com/31930782/72441065-c9dceb80-3788-11ea-8061-0e33fdbe3528.png)
This is the correct Disposition Diagram. the red arrows represent the disposition changes when a STOP MO is received

**Comment by aeatencio** [comment]
It's possible (but not expected) to receive a STOP MO before the respondent disposition is `contacted`
We need to cover this case because the respondent isn't in a final disposition.
So, we'll treat it in the same way we do when the respondent disposition is `contacted`.

```
Queued -> Refused
Contacted -> Refused
Started -> Breakoff
InterimPartial -> Partial
```

**Comment by mmuller** [comment]
Working properly in version f18d5cc
