### ISSUE TITLE
[Histogram] Max scale value is not related to the current stack

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1614]
When the current stack has ~500 the max scale value is 60k

![image (19)](https://user-images.githubusercontent.com/518152/72541927-15af9380-3862-11ea-9629-cbcf51261851.png)

Max scale value: 4
Current stack: 5
![image](https://user-images.githubusercontent.com/518152/72554259-10aa0e80-3879-11ea-98f1-3d9556132074.png)

**Comment by bcardiff** [comment]
Fixed in #1618 due to `@instedd/surveda-d3-components 1.0.18`

**Comment by mmuller** [comment]
Working properly in version a98ec31
