### ISSUE TITLE
Actual success rate shows 100% as soon as survey starts and before contacting starts

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1627]
The `Initial Success Rate` may be OK in the screenshot (it depends on environment info), but the `Actual Success Rate` should be 0 if we haven't contacted anyone.

<img width="649" alt="Screen Shot 2020-01-10 at 19 24 21" src="https://user-images.githubusercontent.com/5470539/73278098-db32e880-41c9-11ea-9096-f65250c4d4b9.png">

**Comment by bcardiff** [comment]
The actual success rate should appear gray with a '0%' when there are no respondets.

**Comment by mmuller** [comment]
Working properly in version 672562a
