### ISSUE TITLE
Duplicate respondents due to sanitized phone depending on channel

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#1639]
If a channel applies a pattern to a the respondent's phone number, Surveda updates the `sanitized_phone_number` field with that so it can find the respondent upon channel's callbacks.

When adding more sample to a running survey, the duplicates detection checks using `sanitized_phone_number` - but without running the numbers through the channel patterns (which could be more than one). This means we can end up with duplicate respondents (maybe even having two respondents with the same `phone_number` but different `sanitized_phone_number`).

We should add a new `canonical_phone_number` that stores the initial sanitation of the number (only digits, no dashes/plus/parens), and use that for dupes checking.

**Comment by mmuller** [comment]
Working properly in version fb9aeb3
