### ISSUE TITLE
Deprecated timezones breaks in Chrome

### ISSUE THREAD

**Issue by anaPerezGhiglia** [instedd/surveda#1653]
**symptom:** 
The "Create Survey" UI fails when selecting "US/Eastern" timezone

**cause:**
The backend returns the list with all the timezones, even those that are deprecated and those that replace the deprecated ones (called links). 

Chrome no longer supports the deprecated timezones ("US/Eastern" links to "America/New_York") 
sources: 
https://stackoverflow.com/a/57711388
http://ftp.iana.org/tz/tzdb-2016g/backward

**solution:**
Surveda uses Timex for getting the timezones, which uses Tzdata that downloads the timezones data every day and has the timezones discriminated by `canonical` or `links`
The TimezoneController should return a map with `timezone -> target_timezone` for all the timezones even if it is a link or not, so the component doesn't have to discriminate. The `timezone` should be use for displaying in the drop-down-list and for configuring the survey schedule, while the `target_timezone` should be used for getting the current time

**Comment by matiasgarciaisaia** [comment]
We should also consider adding a try/catch to the code that tries to render the label with the current time in the selected timezone - that's the one that's crashing right now, and it depends on browsers updating their timezones' DB at the peace they won't.

**Comment by mmuller** [comment]
Working properly in version fb9aeb3
