### ISSUE TITLE
Inconsistent cutoff rules when creating survey

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1666]
When a survey is created the default cutoff rule is "No cutoff" but that option is not shown until a questionnaire is selected.
No questionnaire selected
<img width="1416" alt="noquestionnaireselected" src="https://user-images.githubusercontent.com/31930782/76560009-f78b9b80-647e-11ea-946d-b3ca1abd21d9.png">
Questionnaire selected
<img width="1349" alt="questionnaireselected" src="https://user-images.githubusercontent.com/31930782/76560018-fc504f80-647e-11ea-9cf8-f86e87cbe50a.png">

**Comment by bcardiff** [comment]
Check why do the cutoff rules depend on the selected questionnaire.

Either remove that dependency by showing all the options, or hide all the options when no questionnaire is selected.

**Comment by manumoreira** [comment]
At least No cut off and Number of completes must be available in all cases and No cutoff selected by default

**Comment by manumoreira** [comment]
@bcardiff  can we set no cutoff as default only after editing the schedule and not at the very begging of the survey edition?

**Comment by bcardiff** [comment]
And leaving by default no selection at all so the user need to explictly choose?

**Comment by manumoreira** [comment]
Ok, that would work too.

**Comment by mmuller** [comment]
@bcardiff only the quotas definition depends on the selected questionnaire. The quotas are reset after selecting another questionnaire.

**Comment by mmuller** [comment]
Working properly in version 3ffaf2e
