### ISSUE TITLE
Content in gray footer overflaps with main content

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1670]

**Comment by bcardiff** [comment]
![Screen Shot 2020-03-17 at 15 57 49](https://user-images.githubusercontent.com/459923/76891638-18316800-6868-11ea-8199-790869ff798f.png)

**Comment by danimiba** [comment]
As discussed with @jkicillof, footer should be the color of the background.

**Comment by mmuller** [comment]
Working properly in version ab37075
