### ISSUE TITLE
Session simulator frontend

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1697]
Based on https://github.com/instedd/surveda/pull/1696 implement the UI on https://projects.invisionapp.com/d/main#/console/8374235/385278474/preview .

User should be able to do a full page reload to start a new session.

The chat component WIP is in `feature/sms-simulator` branch
The submission and state controls already exist but they might need to be decoupled from the store since in the simulator the response from the server should be used.

There is no need to store the simulated session in the store. It can all be kept in the state of the page component.

**Comment by mmuller** [comment]
Working properply in version 8fa4cc0
