### ISSUE TITLE
Audio files are not included when importing a questionnaire from another instance

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1708]
**Found in version** c81dd6c

**Steps to reproduce:**
* Navigate to `surveda-stg`.
* Create a Questionnaire.
* Upload an audio file or add a recording to the Questionnaire.
* Export the Questionnaire.
* Navigate to `surveda`.
* Import the Questionnaire.
* Observe the steps content.

**Obtained result:**
* The audio file is not imported.

**Comment by mmuller** [comment]
It may be related to #1536

**Comment by bcardiff** [comment]
* In the exported .zip, there should be a way to link audio resource and steps. Currently, there is a hash and the filenames, but they are not linked.
  * When importing, store the audio as new resources and reference them.

  The exported format should not relay on UUID or hash of the audio files inside it.

  ```
  export.zip
    /quex.json
      audio: { "hello-world.wav" }
    /hello-word.wav
  ```

**Comment by mmuller** [comment]
Working properly in version 643025f
