### ISSUE TITLE
Project memberships must be unique for each project/user pair

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#1721]
Surveda expects each `User` to have a single `ProjectMembership` for each `Project`, but it doesn't check for duplicates before creating new memberships.

![Kapture 2020-05-28 at 12 34 36](https://user-images.githubusercontent.com/5470539/83162234-d92d5780-a0df-11ea-9aaa-2b001bf01759.gif)

_Note: Surveda doesn't let a user add herself to the project - this has to be tested with at least two accounts_

**Comment by manumoreira** [comment]
Duplicated to #2233
