### ISSUE TITLE
Include interim partials in cockpit metrics

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1726]
When a respondent reaches the interim partial disposition it can only go to Partial or Complete so when count partial as complete is selected in the survey settings there's no reason to exclude interim partials from the calculations.
To include interim partials we should add them into:
Exhausted
Partials

So far this change will impact in:

- Progress
- Actual success rate
- Estimated success rate
- Respondents needed
- Available sample

This change creates a more optimistic approach, the success rate will be higher and the number of respondents needed to complete target will decrease.
The positive side of this would be having a more accurate estimation in surveys that are counting partial as completes
The negative side is that as the success rate will increase and the survey might take longer to finish

**Comment by mmuller** [comment]
Working properly in version 643025f
