### ISSUE TITLE
Database deadlocks

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#1744]
We've been observing (in at least 0.25.0, 0.26.0 and 0.26.1) that the application throws some MySQL `Deadlock found when trying to get lock; try restarting transaction` exceptions from time to time. It happens in a couple of different parts of the codebase.

`[error] Ranch listener Ask.Endpoint.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.204.3> exit with reason: {{%Mariaex.Error{action: nil, connection_id: nil, mariadb: %{code: 1213, message: "Deadlock found when trying to get lock; try restarting transaction"}, message: nil, reason: nil, tag: nil}, [{Ecto.Adapters.SQL, :struct, 7, [file: 'lib/ecto/adapters/sql.ex', line: 571]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 469]}, {Ecto.Repo.Schema, :"-do_update/4-fun-0-", 13, [file: 'lib/ecto/repo/schema.ex', line: 277]}, {Ecto.Repo.Schema, :"-wrap_in_transaction/6-fun-0-", 3, [file: 'lib/ecto/repo/schema.ex', line: 691]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 620]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1275]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1199]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 790]}]}, {Ask.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "surveda.instedd.org", method: "GET", owner: #PID<0.204.3>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["callbacks", "verboice", "status", "redacted", "redacted"], path_params: %{}, port: 80, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "CallSid=redacted&CallStatus=ringing&From=redacted&CallDuration=0", remote_ip: {1, 2, 3, 4}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"content-length", "0"}, {"te", ""}, {"host", "surveda.instedd.org"}, {"x-forwarded-port", "443"}, {"x-forwarded-proto", "https"}, {"x-forwarded-for", "redacted"}, {"connection", "close"}], request_path: "/callbacks/verboice/status/redacted/redacted", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}`

`[error] Error deactivating ivr respondent in RetriesHistogram: %Mariaex.Error{action: nil, connection_id: nil, mariadb: %{code: 1213, message: "Deadlock found when trying to get lock; try restarting transaction"}, message: nil, reason: nil, tag: nil} [{Ecto.Adapters.SQL, :struct, 7, [file: 'lib/ecto/adapters/sql.ex', line: 571]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 469]}, {Ecto.Repo.Schema, :"-do_update/4-fun-0-", 13, [file: 'lib/ecto/repo/schema.ex', line: 277]}, {Ecto.Repo.Schema, :"-wrap_in_transaction/6-fun-0-", 3, [file: 'lib/ecto/repo/schema.ex', line: 691]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 620]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1275]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1199]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 790]}]`

`[error] Error removing the respondent in RetriesHistogram: %Mariaex.Error{action: nil, connection_id: nil, mariadb: %{code: 1213, message: "Deadlock found when trying to get lock; try restarting transaction"}, message: nil, reason: nil, tag: nil} [{Ecto.Adapters.SQL, :struct, 7, [file: 'lib/ecto/adapters/sql.ex', line: 571]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 469]}, {Ecto.Repo.Schema, :"-do_update/4-fun-0-", 13, [file: 'lib/ecto/repo/schema.ex', line: 277]}, {Ecto.Repo.Schema, :"-wrap_in_transaction/6-fun-0-", 3, [file: 'lib/ecto/repo/schema.ex', line: 691]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 620]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1275]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1199]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 790]}]`

`[error] Error retrying respondent. Rolling back transaction: %Mariaex.Error{action: nil, connection_id: nil, mariadb: %{code: 1213, message: "Deadlock found when trying to get lock; try restarting transaction"}, message: nil, reason: nil, tag: nil} [{Ecto.Adapters.SQL, :struct, 7, [file: 'lib/ecto/adapters/sql.ex', line: 571]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 469]}, {Ecto.Repo.Schema, :"-do_update/4-fun-0-", 13, [file: 'lib/ecto/repo/schema.ex', line: 277]}, {Ecto.Repo.Schema, :"-wrap_in_transaction/6-fun-0-", 3, [file: 'lib/ecto/repo/schema.ex', line: 691]}, {DBConnection, :transaction_nested, 2, [file: 'lib/db_connection.ex', line: 1366]}, {DBConnection, :transaction_meter, 3, [file: 'lib/db_connection.ex', line: 1226]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 790]}, {Ecto.Repo.Schema, :update!, 4, [file: 'lib/ecto/repo/schema.ex', line: 142]}]`

(all backtraces shown here belong to Surveda 0.26.1)

**Comment by matiasgarciaisaia** [comment]
Enabling [deadlocks printouts](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_print_all_deadlocks) I've managed to identify the deadlocks are generated by the database triggers that keep the `respondent_stats` up to date.

Here's an example:

```
2020-06-18T21:35:34.027779Z 566 [Note] InnoDB: Transactions deadlock detected, dumping detailed information.
2020-06-18T21:35:34.027808Z 566 [Note] InnoDB:
*** (1) TRANSACTION:

TRANSACTION 22600376, ACTIVE 1 sec starting index read
mysql tables in use 3, locked 3
LOCK WAIT 4 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 577, OS thread handle 140402000619264, query id 108941776 10.42.205.242 surveda updating
UPDATE respondent_stats
     SET `count` = `count` - 1
   WHERE survey_id = OLD.survey_id
     AND questionnaire_id = IFNULL(OLD.questionnaire_id, 0)
     AND state = OLD.state
     AND disposition = OLD.disposition
     AND quota_bucket_id = IFNULL(OLD.quota_bucket_id, 0)
     AND mode = IFNULL(OLD.mode, '')
2020-06-18T21:35:34.027839Z 566 [Note] InnoDB: *** (1) WAITING FOR THIS LOCK TO BE GRANTED:

RECORD LOCKS space id 325 page no 8 n bits 192 index PRIMARY of table `surveda`.`respondent_stats` trx id 22600376 lock_mode X locks rec but not gap waiting
Record lock, heap no 49 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000000047; asc        G;;
 1: len 4; hex 8000005d; asc    ];;
 2: len 6; hex 616374697665; asc active;;
 3: len 9; hex 636f6e746163746564; asc contacted;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 00000158dab6; asc    X  ;;
 7: len 7; hex 32000001e72445; asc 2    $E;;
 8: len 4; hex 8000030c; asc     ;;

2020-06-18T21:35:34.028070Z 566 [Note] InnoDB: *** (2) TRANSACTION:

TRANSACTION 22600374, ACTIVE 1 sec inserting
mysql tables in use 3, locked 3
7 lock struct(s), heap size 1136, 4 row lock(s), undo log entries 2
MySQL thread id 566, OS thread handle 140402422155008, query id 108941778 10.42.205.242 surveda update
INSERT INTO respondent_stats(survey_id, questionnaire_id, state, disposition, quota_bucket_id, mode, `count`)
  VALUES (NEW.survey_id, IFNULL(NEW.questionnaire_id, 0), NEW.state, NEW.disposition, IFNULL(NEW.quota_bucket_id, 0), IFNULL(NEW.mode, ''), 1)
  ON DUPLICATE KEY UPDATE `count` = `count` + 1
2020-06-18T21:35:34.028092Z 566 [Note] InnoDB: *** (2) HOLDS THE LOCK(S):

RECORD LOCKS space id 325 page no 8 n bits 192 index PRIMARY of table `surveda`.`respondent_stats` trx id 22600374 lock_mode X locks rec but not gap
Record lock, heap no 49 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000000047; asc        G;;
 1: len 4; hex 8000005d; asc    ];;
 2: len 6; hex 616374697665; asc active;;
 3: len 9; hex 636f6e746163746564; asc contacted;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 00000158dab6; asc    X  ;;
 7: len 7; hex 32000001e72445; asc 2    $E;;
 8: len 4; hex 8000030c; asc     ;;

2020-06-18T21:35:34.028363Z 566 [Note] InnoDB: *** (2) WAITING FOR THIS LOCK TO BE GRANTED:

RECORD LOCKS space id 325 page no 8 n bits 192 index PRIMARY of table `surveda`.`respondent_stats` trx id 22600374 lock_mode X waiting
Record lock, heap no 49 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000000047; asc        G;;
 1: len 4; hex 8000005d; asc    ];;
 2: len 6; hex 616374697665; asc active;;
 3: len 9; hex 636f6e746163746564; asc contacted;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 00000158dab6; asc    X  ;;
 7: len 7; hex 32000001e72445; asc 2    $E;;
 8: len 4; hex 8000030c; asc     ;;

2020-06-18T21:35:34.028593Z 566 [Note] InnoDB: *** WE ROLL BACK TRANSACTION (1)
```

**Comment by matiasgarciaisaia** [comment]
According to [the documentation](https://dev.mysql.com/doc/refman/5.7/en/innodb-locking.html#innodb-record-locks), what seems to be happening is that the first transaction wants to get a row-level lock (`rec but not gap` seams to mean a single record, but not a gap/range-of-rows surrounding it), while the second _holds_ a row-level lock but now wants to lock the whole table (`lock_mode X waiting`, without `rec` or `gaps` additions).

InnoDB places the lock requests in a queue by resource. If there's a pending request for a resource from a transaction, it will block _other_ requests from other transactions until that one gets granted.

The other thing that I've learnt is that MySQL only reports the _current_ query of the transaction - but not the previous, in which it may have gotten the locks.

So my current guess is that the `respondents_upd` trigger is the cause of the issue (transaction 2 above), when it runs along a `respondents_del` (transaction 1 above).

The `respondents_upd` starts running an `UPDATE` on a specific row, for which it needs to get the `rec but not gap` lock. Then a `respondents_del` starts, trying to get the lock to `UPDATE` the exact same record - and it gets queued. After the `UPDATE` of `respondents_upd` completes, it moves on to the `INSERT`, which requires a whole-index lock - and gets queued after the other row-level request, which won't get solved, generating the deadlock.

My theory is that if we start by `INSERT`ing and then do the `UPDATE`, we start getting the wider-lock before the more specific one, and thus we avoid the deadlock.

**Comment by matiasgarciaisaia** [comment]
Just swapping the order of the `INSERT` and the `UPDATE` didn't work. It seems there are some other locks involved here, since the new deadlock involved writing to two different tables:

```
*** (1) TRANSACTION:
TRANSACTION 57163238, ACTIVE 0 sec inserting
mysql tables in use 3, locked 3
LOCK WAIT 8 lock struct(s), heap size 1136, 4 row lock(s), undo log entries 1
MySQL thread id 11253, OS thread handle 140339325073152, query id 381337809 10.42.129.121 surveda update
INSERT INTO respondent_stats(survey_id, questionnaire_id, state, disposition, quota_bucket_id, mode, `count`)
  VALUES (NEW.survey_id, IFNULL(NEW.questionnaire_id, 0), NEW.state, NEW.disposition, IFNULL(NEW.quota_bucket_id, 0), IFNULL(NEW.mode, ''), 1)
  ON DUPLICATE KEY UPDATE `count` = `count` + 1
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 505 page no 16 n bits 288 index PRIMARY of table `surveda`.`respondent_stats` trx id 57163238 lock_mode X waiting
Record lock, heap no 156 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000000189; asc         ;;
 1: len 4; hex 8000017d; asc    };;
 2: len 6; hex 616374697665; asc active;;
 3: len 9; hex 636f6e746163746564; asc contacted;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 000003683de1; asc    h= ;;
 7: len 7; hex 2f000001b423a2; asc /    # ;;
 8: len 4; hex 8000146c; asc    l;;

*** (2) TRANSACTION:
TRANSACTION 57163233, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
10 lock struct(s), heap size 1136, 6 row lock(s), undo log entries 5
MySQL thread id 11267, OS thread handle 140339804833536, query id 381337825 10.42.129.121 surveda update
INSERT INTO `retry_stats` (`attempt`,`count`,`ivr_active`,`mode`,`retry_time`,`survey_id`,`inserted_at`,`updated_at`) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE `count` = `count` + ?
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 505 page no 16 n bits 288 index PRIMARY of table `surveda`.`respondent_stats` trx id 57163233 lock_mode X
Record lock, heap no 156 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000000189; asc         ;;
 1: len 4; hex 8000017d; asc    };;
 2: len 6; hex 616374697665; asc active;;
 3: len 9; hex 636f6e746163746564; asc contacted;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 000003683de1; asc    h= ;;
 7: len 7; hex 2f000001b423a2; asc /    # ;;
 8: len 4; hex 8000146c; asc    l;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 556 page no 42 n bits 376 index id of table `surveda`.`retry_stats` trx id 57163233 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** WE ROLL BACK TRANSACTION (1)
```

Transaction 2 here is waiting on a lock on `retry_stats`, while Transaction 1 is waiting on a lock on `respondent_stats`.

I still don't manage to understand how they are locking each other. It seems MySQL isn't reporting any lock that Transaction 1 is holding (since it starts with `mysql tables in use 3, locked 3` but doesn't list any).

**Comment by ysbaddaden** [comment]
I would say that the culprit is maybe just the use of TRIGGER. We run a bunch of them whenever we INSERT, UPDATE or DELETE a respondent, and I have two problems with that approach:

- the respondent -> stats sync logic is hidden in the database (it should be in the app);
- triggers use shared/exclusive locks (oops -> deadlocks): https://dba.stackexchange.com/a/3409

**Comment by matiasgarciaisaia** [comment]
I understand the decision to move that logic into the database was a thoughtful one - it was not _just because_, but they really considered that, performance-wise, updating the stats from the app's code would not be able to cope with the load the `respondents` table has during a full-scale survey.

That doesn't mean that the solution is the right one. It doesn't even mean the solution _was_ the right one. But I know that hiding the login in the database was a conscious tradeoff back when they made the call.

In light of this information we now have (both _actually being hitting deadlocks_ and that they are most probably caused because MySQL triggers don't play very well with the context), I'm OK with challenging that original decision.

I guess we can move that logic into the app, and perform a couple of tests in heavy-load environments (not starting with a full-scale survey, but maybe run a couple of pre-tests in some country that's about to collect data by the time we have a stable-enough version of this change). This - we should schedule with @manumoreira.

**Comment by manumoreira** [comment]
Thanks, @matiasgarciaisaia for sharing your thoughts and this clear summary. A while ago when this issue was our nightmare we have created the [NCD Twilio simulator](https://github.com/instedd/ncd_twilio_simulator) but never used it, we might want to give it a try...what do you think @ysbaddaden ?

**Comment by ysbaddaden** [comment]
Waj wrote the triggers so I know their usage has been pondered, but I also can't trust MySQL to handle them efficiently. We'd probably have a different experience with PostgreSQL, but I'd still question the need for triggers :shrug: 

I'd like to head back and understand the feature: there is Respondent and RespondentStats, and we need to synchronize the Respondent data into RespondentStats. Yet, do we need it to happen in realtime? Could we have some kind of delay, or was this considered risky because we could end up with out-of-sync errors? Or did we choose triggers because it helped not to bother with all the places that are manipulating respondents?

If we need it to be in realtime, transactions seem to be better implemented in MySQL than triggers, so maybe building some [Ecto.Multi](https://hexdocs.pm/ecto/Ecto.Multi.html) would do the job?

If a delay is acceptable, maybe an async Actor could handle the job, using timestamps to determine whether the data is synchronized or not, and trying to run idempotent queries, always using the latest data?

@manumoreira If we have a stress tool, it would be interesting to try it, and see if we can replicate the issue on a development machine.

**Comment by matiasgarciaisaia** [comment]
`RespondentStats` is a summary of the state of the surveys - data that feed a survey's dashboard counters.

It doesn't have to be _exactly_ real-time, but we want it to be as accurate as possible (a couple of seconds of delay between a respondent changing its state is tolerable, a few minutes not so much - an hour will definitely not be acceptable).

In instances that run full-scale surveys we may have >1M respondents, and active surveys involving ~150k respondents, performing ~15k calls (ie, potential respondents' status changes) a day - and we're trying to improve that number of calls per day.

I really don't recall (if I ever knew) why we chose triggers instead of transactions. I guess it was for consistency reasons (ie, not having to worry about _where in the code_ the changes come from), but I _think_ performance issues were on the table, too.

I think if we can guarantee the Stats being consistent, a small delay would be acceptable.

----

> A while ago when this issue was our nightmare we have created the [NCD Twilio simulator](https://github.com/instedd/ncd_twilio_simulator) but never used it, we might want to give it a try...

We need to re-fix instedd/verboice#878 for the simulator to work.

**Comment by ysbaddaden** [comment]
There aren't that many calls to insert/update/delete a Respondent. We can probably go the transaction route, with an Ecto.Multi and a RespondentStats.sync(respondent) method to append an additional query to the transaction if needed. There should be no delay.

Note: I just found out that `Respondent.changeset()` is using an [optimistic_lock](https://hexdocs.pm/ecto/Ecto.Changeset.html#optimistic_lock/3). That seems to be fine.

**Comment by anaPerezGhiglia** [comment]
Currently on staging it seems as it two triggers are deadlocking each others
```
(1) -> INSERT INTO respondent_stats
     -> WAITING FOR THIS LOCK TO BE GRANTED 
             - index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468595 lock_mode X waiting

(2) -> INSERT INTO respondent_stats
      -> HOLDS THE LOCK(S):
             - index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468596 lock_mode X locks rec but not gap
      -> WAITING FOR THIS LOCK TO BE GRANTED
            - index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468596 lock_mode X waiting
```


```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2024-04-12 11:25:28 0x7f398c429700
*** (1) TRANSACTION:
TRANSACTION 27468595, ACTIVE 0 sec inserting
mysql tables in use 3, locked 3
LOCK WAIT 7 lock struct(s), heap size 1136, 4 row lock(s), undo log entries 2
MySQL thread id 12, OS thread handle 139885143570176, query id 33349478 10.42.161.41 surveda_stg update
INSERT INTO respondent_stats(survey_id, questionnaire_id, state, disposition, quota_bucket_id, mode, `count`)
  VALUES (NEW.survey_id, IFNULL(NEW.questionnaire_id, 0), NEW.state, NEW.disposition, IFNULL(NEW.quota_bucket_id, 0), IFNULL(NEW.mode, ''), 1)
  ON DUPLICATE KEY UPDATE `count` = `count` + 1
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 47 page no 82 n bits 168 index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468595 lock_mode X waiting
Record lock, heap no 78 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000001055; asc        U;;
 1: len 4; hex 80000d70; asc    p;;
 2: len 6; hex 616374697665; asc active;;
 3: len 6; hex 717565756564; asc queued;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 000001a32334; asc     #4;;
 7: len 7; hex 4700000f951e65; asc G     e;;
 8: len 4; hex 80000733; asc    3;;

*** (2) TRANSACTION:
TRANSACTION 27468596, ACTIVE 0 sec inserting
mysql tables in use 3, locked 3
9 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 2
MySQL thread id 10, OS thread handle 139885143037696, query id 33349477 10.42.161.41 surveda_stg update
INSERT INTO respondent_stats(survey_id, questionnaire_id, state, disposition, quota_bucket_id, mode, `count`)
  VALUES (NEW.survey_id, IFNULL(NEW.questionnaire_id, 0), NEW.state, NEW.disposition, IFNULL(NEW.quota_bucket_id, 0), IFNULL(NEW.mode, ''), 1)
  ON DUPLICATE KEY UPDATE `count` = `count` + 1
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 47 page no 82 n bits 168 index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468596 lock_mode X locks rec but not gap
Record lock, heap no 78 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000001055; asc        U;;
 1: len 4; hex 80000d70; asc    p;;
 2: len 6; hex 616374697665; asc active;;
 3: len 6; hex 717565756564; asc queued;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 000001a32334; asc     #4;;
 7: len 7; hex 4700000f951e65; asc G     e;;
 8: len 4; hex 80000733; asc    3;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 47 page no 82 n bits 168 index PRIMARY of table "surveda_stg"."respondent_stats" trx id 27468596 lock_mode X waiting
Record lock, heap no 78 PHYSICAL RECORD: n_fields 9; compact format; info bits 0
 0: len 8; hex 0000000000001055; asc        U;;
 1: len 4; hex 80000d70; asc    p;;
 2: len 6; hex 616374697665; asc active;;
 3: len 6; hex 717565756564; asc queued;;
 4: len 4; hex 80000000; asc     ;;
 5: len 7; hex 5b22697672225d; asc ["ivr"];;
 6: len 6; hex 000001a32334; asc     #4;;
 7: len 7; hex 4700000f951e65; asc G     e;;
 8: len 4; hex 80000733; asc    3;;

*** WE ROLL BACK TRANSACTION (1)
```

**Comment by anaPerezGhiglia** [comment]
adding something more to the "ugly consequences of using triggers" list:
 * The trigger gets attached to the respondent-modifying transaction
    * So if the trigger fails (as when hitting a deadlock), the whole transaction gets rolled back. 
  
This means that we are loosing important business changes - respondent modifications - for updating stats.. 
    
IMO the transaction of updating/inserting a respondent should be as plain as possible - and between the scenarios of 
(1) have respondent updated but stats out of sync with reality and (2) only update respondents if we can keep track of the stats, we definitively want (1) - but the current solution matches with (2) 🫠
