### ISSUE TITLE
SMS Simulator focus on the quex last step

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1748]
When using the sandbox and the SMS simulator the default view of the page is doing focus on the last step of the quex. In most of the cases, it makes losing the view focus from the SMS simulator.
<img width="1678" alt="defaultSMSSimView" src="https://user-images.githubusercontent.com/31930782/85631825-98781e00-b64c-11ea-8ece-6d25752ba915.png">

**Comment by mmuller** [comment]
Working properly in version 2aeea90
