### ISSUE TITLE
[Quiz] Record audio in the browser

### ISSUE THREAD

**Issue by waj** [instedd/surveda#176]
https://projects.invisionapp.com/d/main#/console/8374235/193622674/preview

**Comment by waj** [comment]
Research about media APIs: http://caniuse.com/#search=getUserMedia

Once the user selects the option "Record" from the dropdown, enable this API. That will ask permission to the user the first time.

Research also about audio compression options.

**Comment by nditada** [comment]
Implemented as #1223
