### ISSUE TITLE
Add link to disposition flow chart/wiki in survey overview

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1765]
Add a link to https://github.com/instedd/surveda/wiki/Disposition-flow-chart In the survey overview, at the disposition table in the bottom of the page.

<img width="1339" alt="surveda overview dispo" src="https://user-images.githubusercontent.com/31930782/91355127-1cbd5d80-e7c4-11ea-8161-9c490dece399.png">

**Comment by bcardiff** [comment]
Also
- Add link to gdoc in wiki
- Remove svg from docs folder

**Comment by mmuller** [comment]
Working properly in version ad2b6c3
