### ISSUE TITLE
Archive questionnaires

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1771]
- [x] In quex index by able to select active or archived quex (front-end  / back-end)
- [x] In the quex list allow the user to archive / unarchive (front-end / back-end)
- [x] Show archived questionnaires as read only in questionnaire editor (front-end)
- [x] Don't update archived questionnaires, they aren't updatable (back-end)
- [x] Don't archive questionnaires of not running surveys (back-end)
- [x] Show the user a message when trying to archive a not running survey quex (front-end)
- [x] Duplicating an archived quex should create an active quex
- [x] When creating a survey list only the active quex
- [x] Log archive and unarchive events in activities

**Comment by mmuller** [comment]
Working properly in version da07ac7
