### ISSUE TITLE
Missing message in empty surveys index

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1780]
When a Project doesn't have Surveys the message "You have no surveys in this project" must be displayed.
In version ad2b6c3 that message is missing.

![image](https://user-images.githubusercontent.com/518152/93266708-d9319000-f780-11ea-9cdd-3edd13a2a315.png)

**Comment by bcardiff** [comment]
`folders` is `undefined` and that might cause the issue.

**Comment by mmuller** [comment]
Working properly in version da07ac7
