### ISSUE TITLE
Mobile web simulator

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1785]
Currently, if a user wants to test the mobile web mode needs to have a QST client nuntium channel to send (and receive) the SMS invitation with the link.
It will be useful to implement a mobile web simulator that simply exposes the SMS invitation with a link in the sandbox.

**Comment by bcardiff** [comment]
Expose the respondent's link and _sms message_ using the mobile phone widget. Open the mobile web in new tab or in iframe within the phone widget.
