### ISSUE TITLE
Collaborators can be invited twice to the same project

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1786]
If an Admin or Owner user invites a collaborator twice to the same project no error is shown, but then the project crashes and the UI doesn't work properly.

`{{%Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:\n\nfrom p in Ask.ProjectMembership,\n  where: p.project_id == ^1,\n  where: p.user_id == ^5\n"},`

**Comment by matiasgarciaisaia** [comment]
As of 0.28.0, the backend throws a 500 and logs this error when trying to access the project:

`[error] Ranch listener Ask.Endpoint.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.23835.0> exit with reason: {{%Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:\n\nfrom p in Ask.ProjectMembership,\n  where: p.project_id == ^1,\n  where: p.user_id == ^5\n"}, [{Ecto.Repo.Queryable, :one, 4, [file: 'lib/ecto/repo/queryable.ex', line: 71]}, {Ask.ProjectController, :show, 2, [file: 'web/controllers/project_controller.ex', line: 103]}, {Ask.ProjectController, :action, 2, [file: 'web/controllers/project_controller.ex', line: 1]}, {Ask.ProjectController, :phoenix_controller_pipeline, 2, [file: 'web/controllers/project_controller.ex', line: 1]}, {Ask.Endpoint, :instrument, 4, [file: 'lib/ask/endpoint.ex', line: 1]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 278]}, {Ask.Router, :call, 2, [file: 'lib/plug/error_handler.ex', line: 64]}, {Ask.Endpoint, :plug_builder_call, 2, [file: 'lib/ask/endpoint.ex', line: 1]}]}, {Ask.Endpoint, :call, [ ... redacted ...]`

**Comment by manumoreira** [comment]
Avoid API crashing when user invited twice
