### ISSUE TITLE
Mobile Web simulator appearence

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1799]
While testing the mobile web simulator in surveda-ph noticed two main things to enhance:

- [ ] The mobile web form height exceeds the height of the quex steps
![screencapture-surveda-ph-org-projects-25-surveys-348-simulation-mobileweb-2020-10-29-01_54_54](https://user-images.githubusercontent.com/31930782/97527408-fc5b7c00-1989-11eb-80da-56a83e23c986.png)

- [ ] There's no simulation channel in the sandbox (even if this simulator doesn't work as the SMS one, it would be nice to show a simulation option)

**Comment by manumoreira** [comment]
The main challenge with the simulator as it is is the lack of available channels for most of the users. To use a channel in the sandbox the user needs to own it. Ideally, it would be great to have a nuntium qst client created for those who can edit a mobile web questionnaire.

**Comment by mmuller** [comment]
Working properly in version 0.30.0
