### ISSUE TITLE
Problems with audio files when exporting questionnaire

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1800]
Found in version [567ce25](https://github.com/instedd/surveda/commit/567ce25dbad6fd8eef764c756aff19e2506725d1)
**Preconditions:**

- There is a Questionnaire Q.
- Q has enabled the Phone call mode.
- Q has a Step S.
- Q has an uploaded audio file for Thank You message or an uploaded audio file for Language Selection

**Steps to reproduce:**

- Navigate to the Questionnaire Q.
- Add audio files to all the steps including Language Selection and/or Thank you message.
- Export Q.
- Observe the exported file.
- Obtained result:

The audio files for Language Selection and Thank you message are not included

**Examples**

- WIth Language Selection and Thank you message https://surveda.instedd.org/projects/355/questionnaires/1091/edit
- Only with Thank you message https://surveda.instedd.org/projects/355/questionnaires/1093/edit

**Comment by aeatencio** [comment]
There are several errors regarding questionnaire export.

1. [Here](https://surveda.instedd.org/projects/355/questionnaires/1093/edit), the export fails.
2. [Here](https://surveda.instedd.org/projects/355/questionnaires/1091/edit), the export doesn't fail, but the exported file is uncompleted and broken. It can't be imported.
3. Also, the algorithm introduced in #1832 doesn't support questionnaires with sections.

We'll tackle the above bugs one by one after #1867, writing specific unit tests and fixing them.
