### ISSUE TITLE
Audios and text data from deleted languages are included in the quex export

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1801]
Found in version 567ce25
**Preconditions:**

- There is a Questionnaire Q1.
- Q1 has enabled the Phone call mode.
- Q1 has a Step S.
- Q1 has more than one language
- There is a Questionnaire Q2 (a copy of Q1 that has only one language)

**Steps to reproduce:**

- Navigate to the Questionnaire Q1.
- Add audio files to all the steps in all languages
- Export Q1.
- Create a copy of Q1 called Q2
- Export Q2.
- Observe the exported files.
- Obtained result:
- The audio files of the deleted languages are included in Q2

**Examples**

- Multi language https://surveda.instedd.org/projects/355/questionnaires/1091/edit
- One language (copy of Multilanguage and deleted language) https://surveda.instedd.org/projects/355/questionnaires/1092/edit

-

**Comment by aeatencio** [comment]
This issue isn't about the audios only, it's about all the questionnaire configuration associated with the deleted language.

We want to preserve the configuration of the original questionnaire, but avoid exporting it.
