### ISSUE TITLE
Allow creation of a new ocurrence of a panel survey via API

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1803]
- It should NOT cancel the latest occurrence if it's still running
- It should create a new survey within the same panel_survey_group_id
- It should flag the new survey as the latest occurrence
- It starts the new survey
- It should validate that the survey has a panel_survey_group_id
- Respondent ids should be preserved along the group
  - The encryption algorithm should take into account the panel_survey_group_id when it's != nil

**Comment by manumoreira** [comment]
Small clarification: the creation of a new occurrence will not be responsible for cancelling the latest occurrence, but it should be completed or cancelled to get be able to be repeated.

**Comment by bcardiff** [comment]
- discuss: which respondents should be promoted to the new repetition?
    - all but refused respondents should be promoted
- discuss: how to handle respondent group and multiple channels?
    - s1: 
        - rg1: 
            - jdoe channel1/channel2
        - rg2: 
            - sdoe channel1/channel2
        - rg3: 
            - rdoe channel3
      - s2:
        - rg-channel1-channel2:
            - jdoe channel1/channel2
            - sdoe channel1/channel2
        - rg-channel3
          - rdoe channel3
    - In the new incarnation there should be a rgX for each channel combination needed.
    - respondents should use the same channel
    - respondents will start from the beginning even if the fallback channel was reached.
- discuss: how does quex comparissons work?
    - not supported for now
    - should be disable that from the UI
- discuss: how does mode comparissons work?
    - not supported for now
    - should be disable that from the UI
- discuss: what happen if the channel is removed before creating the incarnation.
    - pending: to be design a replace screen

**Comment by mmuller** [comment]
Working properly in version 0.30.0
