### ISSUE TITLE
Show an option to start a new occurrence of a panel survey

### ISSUE THREAD

**Issue by bcardiff** [instedd/surveda#1804]
- https://projects.invisionapp.com/d/main#/console/8374235/286487531/comments
- After creation it should go to the new survey overview

**Comment by aeatencio** [comment]
Epic: #1805

**Comment by bcardiff** [comment]
Ref: https://github.com/instedd/surveda/issues/1803#issuecomment-731474378

The buttons should appear disabled if the survey is still ongoing, and show a caption that that is the reason.

**Comment by aeatencio** [comment]
![Repeat survey button](https://user-images.githubusercontent.com/39921597/100449288-6bfc7e00-3092-11eb-94a9-6dcba1d3bdff.png)
