### ISSUE TITLE
Allow setting end date of survey's schedule

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1839]
The survey will be stopped automatically on that date. This is equivalent to cancelling the survey.

**Comment by manumoreira** [comment]
<img width="1484" alt="start-enddates surveda" src="https://user-images.githubusercontent.com/31930782/107802637-5ff29500-6d40-11eb-87a8-461931f4a33d.png">
This can work as a temporary mockup

**Comment by aeatencio** [comment]
Avoid replicating the `end_date` property on survey repetition. 

Copy [this](https://github.com/instedd/surveda/blob/507e02551ebd55d88de7f74e4c7d489b2073c456/lib/ask/runtime/panel_survey.ex#L28) `start_date` property behaviour on survey repetition.

**Comment by mmuller** [comment]
Working properly in version 7235dc9
