### ISSUE TITLE
Improve the UI for panel surveys

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#1856]
Change the look and feel of the latest occurrence of a panel survey card [this way](https://invis.io/2TMXFAVHVQM#/180693793_Surveys)

Also, hide the cards of the other occurrences of the panel survey.

When a panel survey has a only survey, show it and link it the same way as panel surveys with multiple occurrences.

When the panel survey is selected, show all the panel survey occurrences using the same design of the [survey folders](https://invis.io/2TMXFAVHVQM#/378385603_Survey_Menu_-_Folder)

Change the `add survey` button of the folder page for a new `repeat` button, without removing the current `repeat` button on the panel survey overview. 

Review if the name of the panel survey occurrences should stay editable.

For #1805

**Comment by aeatencio** [comment]
Related to #1815

**Comment by mmuller** [comment]
Working properly in version 7235dc9
