### ISSUE TITLE
'end_date' of survey's schedule should stop 5 minutes after the last survey activity window ends

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1859]
If I select `Mar 18, 2021` as `end_date`, the survey should be stopped 5 minutes after the last survey activity window before `Mar 18, 2021` at `23:59:59` ends. So if the last survey activity window ends Mar 18, 2021 at 3 PM, the survey should end Mar 18, 2021 at 3:05 PM 

![image](https://user-images.githubusercontent.com/518152/111527634-e6830380-873e-11eb-8332-a8b0c886095d.png)

**Comment by aeatencio** [comment]
Check the end-user message is fixed while verifying this issue. See [this comment](https://github.com/instedd/surveda/issues/1601#issuecomment-818107998).

**Comment by aeatencio** [comment]
@mmuller before verifying this issue please read the #1862 description.

**Comment by aeatencio** [comment]
@mmuller please consider the #1862 description while verifying this issue. Thanks!

**Comment by mmuller** [comment]
Working properly in version f4c69e6
