### ISSUE TITLE
Edit panel survey occurrence

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1902]
In an occurrence of a Panel Survey a  user should be able to edit:
- start and end date
- respondents groups
- schedule
- modes (primary and fallback)
- channel

Depends on #1887

**Comment by aeatencio** [comment]
On the 1st occurrence, before the survey launch:

- Enabling the `generates_panel_survey` toggle will hide the Comparisons and Cutoff rules.
- Disabling the same flag will show the Comparisons and Cutoff rules again (if something was set up, it will be preserved).

After launching the 1st occurrence (for every occurrence, including the 1st one):

1. The Comparisons and Cutoff rules will remain hidden (they won't show up again, ever).
2. The questionnaire selection will be disabled.
3. The `generates_panel_survey` toggle will be hidden forever.

**Comment by aeatencio** [comment]
For now, don't disable the questionnaire selection and make the user select a questionnaire for every occurrence.
