### ISSUE TITLE
Panel survey view doesn't update when creating/deleteing ocurrence

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1903]
When creating a new occurrence of a panel survey or delete an occurrence hard refresh is needed to get the view updated.
Steps to reproduce:
- Create a panel survey (launch and complete the first occurrence)
- In the panel survey view create new occurrence and before launching go back to the panel survey view
- The new occurrence will not be shown
- Hard refresh, it will be shown
- Delete the last occurrence (still in edition) and the occurrence will still be shown
- Hard refresh......

For #1886

**Comment by mmuller** [comment]
Now (version acf7266) the new occurrence is shown, but it is shown as `Editing` instead of `Running`.

![image](https://user-images.githubusercontent.com/518152/124638908-e62f8500-de61-11eb-96c8-4dcef2022595.png)
