### ISSUE TITLE
All panel surveys occurrences should be shown as a panel surveys

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1918]
There's only one case in which this is not happening:
If a user is editing the settings of the first occurrence of a panel survey before launching and it just leaves the edition the survey will look like a standard survey from the project overview. It should look like a Panel Survey in the project overview.

**Comment by manumoreira** [comment]
According to the discussion we had today July 1st, 2021 it would be enough if the PS survey is created when the edition of the first occurrence starts and not when it is launched

**Comment by aeatencio** [comment]
> It would be enough if the PS survey is created when the edition of the first occurrence starts and not when it is launched.

I've just realized this approach clashes with the end-user giving a name to the panel survey. If the panel survey is created at the same moment of its first occurrence, it can't take its name from it, as it's being done now.

Maybe fixing #1909 is enough to continue with this approach, but I'm not sure. We should re-think this together, if possible.

cc: @manumoreira @anaPerezGhiglia
