### ISSUE TITLE
Change new panel survey wave icon

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#1948]
Currently, we are using [replay icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Areplay%3A) we should replace that one with [repeat one icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Arepeat_one%3A)

**Comment by ysbaddaden** [comment]
I think I misunderstood, and we're talking about this button:

![Capture d'écran du 2021-10-04 14 52 06@2x](https://user-images.githubusercontent.com/47380/135854699-053cdfe2-edca-4486-ab16-c748d23b80de.jpeg)
