### ISSUE TITLE
Enhance survey loading process in project overview

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#1954]
The survey loading process has very bad performance, every time a user opens a project all surveys in the project are loaded.
## Details
Surveys can be in the project root, in a project folder, or in a panel survey (a survey that holds many repetitions of a survey)
So apart from basic pagination, we should also control the loading of the surveys in folders and panel surveys.

We do not have a selected approach for this, ideas are welcome

**Comment by ysbaddaden** [comment]
1. Downloading each survey leads to another issue: **we download the stats** for all surveys (for the graph?), when we should only download those for the currently visible ones. We would greatly reduce the number of requests.

2. We can patch the component that loads surveys, to only load surveys for the current view, meaning the surveys at the root (directly created on the project) or inside a specific folder or inside a specific panel survey. That would start improving things.

3. We could paginate on the server, it wouldn't be too complex inside a folder or panel, but it will prove more complex at the root, where we're mixing resources (panels and surveys), thought folders seem to be displayed separately, and are never paginated?

**Comment by ysbaddaden** [comment]
Some more digging:

- `/api/v1/panel_surveys` includes all `occurrences` for a Panel Survey, which means we download the surveys for a Panel Survey _twice_ in `SurveyIndex`'s component. We don't need the occurrences, just an information about its latest occurrence is enough.
- `/api/v1/` Folder doesn't include their Survey nor PanelSurvey. They're filtered from the while list of Surveys.

Furthermore, the `SurveyShow` component will request **all folders, surveys and panel surveys** just to display the breadcrumb in the page header (Projects > Project > Folder > Panel Survey). I believe we can do better.

**Comment by ysbaddaden** [comment]
Merged into the `develop` branch.
