### ISSUE TITLE
Replace occurrence by wave

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#1972]
In the context of survey research, the term wave is widely used to refer to an instance of a survey. We might want to replace occurrence by wave in the code to keep the terms aligned between code and UI.

**Comment by ftarulla** [comment]
Search for `ocurrence` (note typo: missing `c`)

**Comment by ftarulla** [comment]
In addition to:
- [ ] occurrence

The following typos must be taken into account:
- [ ] occurence
- [ ] ocurrence
- [ ] ocurence

**Comment by diegoliberman** [comment]
Testing guidelines: can we create panel surveys? can we create waves? can we be happy?
