### ISSUE TITLE
Move panel surveys to a folder

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1981]
## Use case
As a user, I want to be able to move a panel survey (with all its waves together) across any folder

## Details
When creating the panel surveys we decided to leave this feature for the future, a user can create a panel survey inside a folder but not move it to another.  This decision was based on complexities around the panel survey data model and the use of the folder id (if I remember correctly)

**Comment by mmuller** [comment]
Panel surveys with `running` and `terminated` states can be correctly moved to folders.
