### ISSUE TITLE
Upgrade Ecto (v2 -> v3)

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#1984]
Ecto itself doesn't seem hard to upgrade.

A potential issue is around calendar types, such as `DateTime`. Elixir 1.3 added calendar types (e.g. `DateTime`). Ecto 2.1 added support for these types, Ecto 2.2 deprecated `Ecto.DateTime` and Ecto 3 removed it. We also rely on `Timex`, and have columns in the database as `Timex.Ecto.DateTime` but the latter is abandoned, since it's incompatible with Ecto 3 and it won't be fixed. It's supposedly not needed anymore since Elixir introduced calendar types.

Breaking changes:
- `Ecto.DateTime` => `:naive_datetime`;
- `Ecto.DateTime.cast/1` => ???
- `Ecto.DateTime.cast!/1` => ???
- `Ecto.DateTime.utc/0` => ???
- `Timex.Ecto.DateTime` => abandoned without replacement.
- `Timex.Ecto.DateTime.autogenerate/0` => ???

We also use `Timex.Timezone`, but don't use `Timex.Ecto.DateTimeWithTimezone` so timezones may not be a problem?

Some links on the issue:

- https://github.com/bitwalker/timex_ecto/issues/85
- https://github.com/elixir-ecto/ecto/issues/2770
- https://elixirforum.com/t/how-to-upgrade-an-app-using-timex-ecto-to-phoenix-1-4-and-ecto-3-0/17676

Note: possible blocker to #1975

**Comment by diegoliberman** [comment]
@ysbaddaden would you like to add a description here?  We added this upgrade to this iteration because this is blocking me to implement https://github.com/instedd/surveda/issues/1975 properly.

**Comment by ysbaddaden** [comment]
[coherence](https://github.com/smpallen99/coherence) must also be upgraded, because the version we depend on (v0.3.2) uses `timex_ecto`, but newer releases don't.

AFAIK we don't need to use our [own fork](https://github.com/manastech/coherence), which has only 1 commit (fixes a warning).

**Comment by ysbaddaden** [comment]
Hopefully, I can migrate away from Ecto.DateTime and Timex.Ecto without having to upgrade Coherence, Timex, or even Ecto itself, I don't even have to remove the Timex.Ecto dependency, because Surveda runs Ecto 2.2 which supports both solutions :candy: :candy: :candy:

**Comment by ysbaddaden** [comment]
Merged into the `develop` branch.

**Comment by diegoliberman** [comment]
This issue requires some overall regression testing of Surveda.
