### ISSUE TITLE
Quex export CSV isn't working

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1995]
Quex CSV export is not working properly, the export crashes sometimes and when it doesn't it does not include the randomized sections.

This feature was created long before adding most of the current quex features.

Depending on quex export epic #1988

**Comment by ysbaddaden** [comment]
@manumoreira I can't reproduce any issue with the "Download contents as CSV" feature of questionnaires. I can download, write a translation, and import them back.

I tried simple questionnaires, and more complex ones, with flags, sections and randomized sections: I always get all the translatable strings.
