### ISSUE TITLE
IVR simulation if no answer repeat questions 3 times then breakoff

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2003]
To emulate the real IVR behavior if there is no answer after 3 seconds we should repeat the question 2 more times and if no answer after that flagged as a breakoff

**Comment by mmuller** [comment]
Version b6ec048

If the question is not the first one, the respondent is flagged as a `break-off` as expected, but when there is no answer to the `first` question, the respondent is flagged as a `refused`:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/518152/154565588-fb424980-a20f-48e2-a08f-09a273b977c0.png">

**Comment by diegoliberman** [comment]
@mmuller shouldn't we create an issue for the bug you mentioned?

**Comment by ysbaddaden** [comment]
Here is the reason: we don't have an endpoint to tell the backend to break-off the simulation, since sending a STOP message did the trick, we used that for now.

@diegoliberman yes, let's create an issue about it!
