### ISSUE TITLE
Audio files are still not cached by HTTP clients/proxies

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2008]
Uploaded and TTS audio files should be cached by browsers since #807, but they apparently aren't in practice:

```console
$ curl -I https://surveda-stg.instedd.org/audio/3df6834f-8a97-4330-86fc-1925981e5e66.mp3
HTTP/1.1 200 OK
server: Cowboy
date: Mon, 06 Dec 2021 13:47:53 GMT
content-length: 58797
cache-control: max-age=0, private, must-revalidate
strict-transport-security: max-age=31536000
x-request-id: Fr4uh4GY_P5_HQwABm5x
content-type: audio/mpeg
content-disposition: attachment; filename=manas-edad.mp3
```

Notes:
- the `max-age=0, private, must-revalidate` prevents any caching by HTTP clients/proxies;
- the `cache-control` headers are properly set in [AudioController](https://github.com/instedd/surveda/blob/bd5cae42d2b832af76782b2fdcf868657376d613/web/controllers/audio_controller.ex).

We should review why the actual `cache-control` gets overwritten, and maybe set the `Expires` and `Last-Modified` headers, and maybe support the `If-Modified-Since` request header, too (replying with a 304 Not Modified), at least for the uploaded audio files.

**Comment by ysbaddaden** [comment]
[plug](https://hex.pm/packages/plug) is setting the `cache-control` header to `max-age=0 private must-revalidate` by default (see [Plug.Conn](https://github.com/elixir-plug/plug/blob/f7fbe26e7148374c4d37bde41540be2844056aa1/lib/plug/conn.ex#L194)) which may imply that we don't set the header properly.

**Comment by matiasgarciaisaia** [comment]
> we do set the cache-control header to a 1 year cache expiry, and this is enough for browsers to cache the response forever

But this is not what we're seeing in production/staging. I guess you needed to change the code somehow to change the `cache-control` header to see the 1-year cache expiry?

As long as we see a response like the one in the first post of this issue, client's are not going to cache that.

So we're either failing to ask Plug to change the cache headers, or we have _something_ else in the request/response path (the reverse proxy?) that's breaking that header.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia I didn't change anything:

**Comment by ysbaddaden** [comment]
Oh, that might be _another_ endpoint. Checking...

**Comment by ysbaddaden** [comment]
Found it. That endpoint doesn't set the cache-control header! I'll have a patch ready tomorrow morning.

```elixir
  scope "/audio" do
    pipe_through :mp3_api
    get "/:id", Ask.AudioDeliveryController, :show
  end
```

**Comment by matiasgarciaisaia** [comment]
_Oh no._ Awesome!

We could also check if we changed which of both URLs we're sending Verboice for the calls - maybe this worked OK a couple of years ago and then we changed which URL we're exposing on the TwiML?

It sounds totally reasonable to add the cache headers in _both_ endpoints anyway.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia I think the API endpoint needs authentication (private), when the other one doesn't (public), and is thus used for external services like Twilio. It seems to also double as always returning a compressed MP3 file.

**Comment by ysbaddaden** [comment]
Verified by @matiasgarciaisaia :
https://github.com/instedd/surveda/pull/2013#issuecomment-989809549
