### ISSUE TITLE
Use "main" as the default branch

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2014]
Some InSTEDD projects migrated from the default `master` branch to a `main` branch, but Surveda didn't (yet). It's starting to be confusing to still have a `master` branch, so let's move on!

See <https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch>.

Developers will then have to run a [few commands](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) to update their local clones.

**Comment by matiasgarciaisaia** [comment]
Instead of renaming the branch, let's create a new `main` one, use it as we're currently using `master`, then update the repo's default branch - so we avoid every developer having to execute a couple of obscure-ish git commands locally.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia I created the `main` branch and changed pull requests to target it. It's ready to become the default branch!

**Comment by matiasgarciaisaia** [comment]
👍 I've just updated the default branch, protected `main` as `master` was, and updated the build script so it handles `main` as `master`. I can't recall anything else that should be taken care of.

**Comment by ysbaddaden** [comment]
Thank you!

**Comment by ysbaddaden** [comment]
@mmuller Nothing to QA on this issue, I'm just keeping it here to verify that images are properly built.

**Comment by ysbaddaden** [comment]
And yes it is: https://github.com/instedd/surveda/runs/4777188192 :tada:

**Comment by matiasgarciaisaia** [comment]
I've just deleted the `master` branch from the repo. For reference, it was pointing to `520ea0df064074cf286cf5f71088b41afdffd097`.
