### ISSUE TITLE
Prepared statements has too many placeholders error in production

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2021]
There is both error and a performance issue in `RespondentGroupAction.remove_duplicates_with_respect_to/2`.

The `respondents.canonical_phone_number` is missing an index, and the SQL query generated by Ecto places too many arguments in the prepared statement, leading to a "Prepared statements has too many placeholders" error in a production server.

See (SURVEDA-MUMBAI-1E](https://sentry.io/organizations/instedd/issues/2852043788/?project=1497371)

**Comment by diegoliberman** [comment]
Triggering: CSV with more than 20 thousands respondants in the Survey
