### ISSUE TITLE
Delete panel surveys

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2029]
Add a Delete option for panel surveys.

Currently, inside a panel survey a user can delete `waves` one by one, as far as there is more than one `wave`, when there's only one `wave` it cannot be deleted from this view.
We should add an option for deleting the whole panel survey.
From the survey index if the user clicks on a panel survey card menu and selects delete all the `waves` and the panel survey itself will be deleted.
A warning dialog should be added
<img width="821" alt="Screen Shot 2022-01-10 at 13 18 39" src="https://user-images.githubusercontent.com/31930782/148801017-4d595eb6-eaee-4f78-b7e8-ae8f1a30c279.png">
The wording would be:
[title] Delete Panel Survey [title]
[warning red uppercase text] Survey deletion cannot be undone [warning red uppercase text]
[paragraph] You are about to delete all the waves of this panel survey. [paragraph]
[paragraph] All the information of the n haves will be lost.[paragraph]
Add Understood checkbox (this will enable the delete button)
[Delete button][Cancel button]

**Comment by ysbaddaden** [comment]
Depends on #2031

**Comment by mmuller** [comment]
Version https://github.com/instedd/surveda/commit/b6ec048fc804383efaf1ce3e656a901e5d0e5688

Panel surveys with `terminated` state can be deleted.
Panel surveys with `running` state can be deleted, and as expected the respondents are not contacted anymore.
