### ISSUE TITLE
[Bug] Respondent incorrectly flagged as refused

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#2052]
Reported [here](https://github.com/instedd/surveda/issues/2003#issuecomment-1043470498).

If the question is not the first one, the respondent is flagged as a `break-off` as expected, but when there is no answer to the `first` question, the respondent is flagged as a `refused`:

![image](https://user-images.githubusercontent.com/25181052/155197431-1890bee5-3c64-4728-ad60-d128b615ed8a.png)

**Comment by ysbaddaden** [comment]
This one is interesting to start digging into `Ask.Runtime` :building_construction: 

Looking into Surveda's internals, I see that we this is a failed channel situation. For example Verboice's channel eventually calls `Ask.Runtime.Survey.channel_failed/3` with a `no-answer` reason. I think we can skip `channel_failed/3` and call `failed_session/2` directly.

We must add a mean for the frontend to report the failure to AskWeb.QuestionnaireSimulationController (e.g. with a new `failed` controller action). The Ask.QuestionnaireSimulator and Ask.QuestionnaireIvrSimulator modules must evolve to handle this case and fail the current session.

**Comment by mmuller** [comment]
Working properly in version 3ac99be
