### ISSUE TITLE
Add ellipsis on step text detail in the mobile phone emulator [IVR Simulator]

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2053]
Currently, when a step is reproduced in the simulator it also shows the text detail of the step in the mobile phone emulator

<img width="1619" alt="Screen Shot 2022-03-02 at 14 11 54" src="https://user-images.githubusercontent.com/31930782/156412958-caad78f0-02a8-4bc7-8546-ac97bcfb856b.png">
<img width="1619" alt="Screen Shot 2022-03-02 at 14 12 00" src="https://user-images.githubusercontent.com/31930782/156412937-74663b88-6f71-4058-846e-8ab603f709bc.png">

When the text exceeds 140 characters or 6 lines the emulator automatically scrolls down to show the last characters of the step.

To enhance the UX we should add a clickable ellipsis after 140 chars or 6 lines, this way the user will always see the first lines of the step by default and only scroll down to the last lines after clicking on the ellipsis.

**Comment by ysbaddaden** [comment]
![Capture d'écran du 2022-04-08 20 24 55@2x](https://user-images.githubusercontent.com/47380/162499947-84fdfb43-6ae1-40cd-abb5-3c8bce097278.jpeg)

@manumoreira It's not evident that the bubble can be clicked to expand the whole text... I'll add at least a CSS class to show that we can have a 'clickable' bubble (pointer cursor). Maybe we could have an explicit `(click to expand)` message?

**Comment by ysbaddaden** [comment]
I made the bubble 'clickable' with a pointer cursor, and added a "Click to expand message" tooltip.
