### ISSUE TITLE
Add chart for daily success rate in survey overview

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2054]
The success rate of a survey can have a wide range of values during a survey, it will be helpful to visualize the changes in this rate throughout the survey. 
As the survey overview is quite crowded with charts currently we might want to reorganize them to get this issue done.
- An option can be to include this into the big line chart for quotas completion at the top of the screen.
[Mockup](https://projects.invisionapp.com/d/main#/console/8374235/241966468/preview)

**Comment by ysbaddaden** [comment]
First things first: to understand what the success rate is. At first glance, it looks like this is the number of completed respondents. On a closer look, if there are any quota buckets, then this is the minimum value of `count` or `quota` in those buckets.

Each respondent is present in `respondent_stats`, so we should be able to filter by state=completed and get the history. I'm not sure this will be needed, but we also have an estimated success rate, so we should be able to scale the success rate (if needed).

Quota buckets, on the other hand, are incremented as counters in `quota_buckets`, so we can't use this value (no history) but we're apparently capable to display a history of each quota, so we should be able to. I'm still looking.

**Comment by ysbaddaden** [comment]
The success rate is a mere count of [completed respondents](https://github.com/instedd/surveda/blob/3ac99bef6903518f4f5b4e7ba70585670b013b03/lib/ask/survey.ex#L596) (+ sometimes partial/interim partial) divided by the count of [exhausted respondents](https://github.com/instedd/surveda/blob/3ac99bef6903518f4f5b4e7ba70585670b013b03/lib/ask/survey.ex#L667) (failed, completed, ...).
