### ISSUE TITLE
Sanitized phone numbers not reset when changing to a channel without patterns

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#2055]
When we start contacting a respondent via a channel, we apply the channel's pattern to make the `sanitized_phone_number` match the one that the channel will use.

This is the relevant code:

https://github.com/instedd/surveda/blob/b6ec048fc804383efaf1ce3e656a901e5d0e5688/lib/ask/runtime/session.ex#L456-L466

When there's a multi-modal survey in which the first mode has a pattern and the second one does not, the `sanitized_phone_number` for the second mode remains unchanged (ie, with the pattern from the mode channel applied).

If there's no pattern, we should reset the `sanitized_phone_number` to the `canonical_phone_number`.

**Comment by matiasgarciaisaia** [comment]
On a larger sense, we should review if `sanitized_phone_numbers` are useful at all.

Maybe we should drop them, use `canonical_phone_number` for every purpose, and make the responsibility of each `Channel` to convert the numbers the telco sends to the `canonical_phone_number` (through the pattern) before doing any operation, and the other way round (ie, work as an Adapter).

**Comment by ysbaddaden** [comment]
I agree. Storing the sanitized phone number is good if it's always the same (for _all_ channels), but if each channel can have its own pattern, then they shouldn't update the respondent, and only transform on-the-fly.

**Comment by ysbaddaden** [comment]
There aren't many places where we need the sanitized phone number. In all but one of these cases we could apply the patterns on-demand, and don't need to persist it on the respondent.

There is one place though where we need the sanitized phone number to be persisted: [`Ask.Runtime.NuntiumChannel.callback/3`](https://github.com/instedd/surveda/blob/main/lib/ask/runtime/nuntium_channel.ex#L98-L105). We use it to find the Respondent from the database when receiving a HTTP notification from Nuntium. Another callback uses the respondent id, but this specific callback doesn't have one, and Nuntium only knows about the sanitized phone number.

**Comment by ysbaddaden** [comment]
I assume a Respondent should only ever be associated to a single channel, isn't she?

I guess `Ask.Runtime.Session.apply_patterns_if_match/2` could reset `sanitized_phone_number` when there are no pattern to apply. If it didn't change previously then it's a NOOP, but if it was changed for another channel, then it will be reset?

**Comment by matiasgarciaisaia** [comment]
> I assume a Respondent should only ever be associated to a single channel, isn't she?

At a single point in time, yes. But they may change between two different channels during a survey. They first get attempted through their respondent group's main channel, then they may fall back to the secondary one in multi-mode surveys.
