### ISSUE TITLE
Manage channel loads

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#2084]
### Epic

As a Survey Editor, I want ALL contacts to be sent in the correspondent time window and without losing any potential survey feedback.

### Context
Stop spamming Verboice/Nuntium!

Given Verboice and Surveda communication process when sending thousands of contacts at once we are stressing the communication without a real necessity.

- **Verboice** calls have an expiry time window, after which pending calls will expire.

  In a scenario where Verboice has capacity to send 10k, and Surveda has a 100k contacts, it will send 100k contact requests, of which 90k will expire. This generates a callback to Surveda for each one of the 90k. This huge amount of callbacks overloads the surveda servers and can lead to miscellaneous failures.

- **Nuntium** doesn’t have a limit of SMS messages. It doesn't have any expiry either. If it receives 100k, it will process them until it finishes. This might mean that messages get sent outside the survey's time window, so people might receive the SMS at unusual hours. People may even get follow-up questions of a survey hours after!

### Acceptance criteria

- Surveda musn’t overload the Verboice and Nuntium servers, it should overload the queue (to avoid latencies) but by an acceptable multiplier (e.g. 2 upto 5 times) not push _everything_.
- SMS messages musn’t be sent outside of the defined survey time window.
- The entire system should minimize the quantity of contacts that fail to be attempted.

### Proposal

Introduce a ChannelBroker between Surveda's Broker and the actual Channel provider (VerboiceChannel, NuntiumChannel) for each Channel registered in Surveda. This new ChannelBroker shall rate limit how many requests are actually made to the corresponding servers.

- The Broker shall send all requests to the individual ChannelBroker (instead of the external servers);
- The ChannelBroker shall send only N requests at any given time (N = channel capacity);
- The ChannelBroker shall monitor outgoing requests, meaning that channel callbacks should now be handled by the ChannelBroker, or be the one notified by Surveda;
- The ChannelBroker shall regularly refill the queue from the pending list of requests (until it's emptied);
- The ChannelBroker shall declare expired pending requests as such to Surveda (internal call), and never send them to the external servers.

Bonuses:

- The Broker could specify a priority (`:low`, `:high`) to requests, so the ChannelBroker may start filling the queue with high priority requests (e.g. followup questions) then send low priority ones (e.g. initial contacts);
- The ChannelBroker could consider a request without a feedback within XX minutes as no longer active (and close it/report it as such).

**Comment by matiasgarciaisaia** [comment]
Thinking in terms of implementation, I don't think I'd have a strong opinion regarding on how to implement the brokers (if a single `ChannelBroker` per Surveda instance, or one per channel type - ie, `VerboiceBroker` vs `NuntiumBroker` -, or if one per channel).

I think the current [Survey]Broker is a single one per Surveda instance, that goes through every active Survey. If you think something analogous to that will make it, that's OK. If not, feel free to do it different - whatever is easier/better to implement.

Remember that a single Survey can use multiple channels (one or two channels per respondent group), and a single channel may be used in multiple surveys at a time.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia The way I see it (for now) is that the survey broker keeps deciding which channel to use for each contact, but will now do so through a channel broker, that will buffer the requests to the external service, delegating to the actual channel to execute the request to the external service.

Then we can start enhancing it, the most obvious being to expire calls within the queue, bypassing the whole channel -> external server -> callback for a single internal function call.

I believe it would be enough for starters?

I don't think we need to customize such a channel broker for each channel type. Unless we decide to push some channel logic into the channel broker?

**Comment by matiasgarciaisaia** [comment]
The overall/high level plan sounds good.

I guess the rest of the decisions will become a bit more obvious as you start working on them - I wouldn't try that much to anticipate them 👍
