### ISSUE TITLE
Error in Nuntium callback

### ISSUE THREAD

**Issue by diegoliberman** [instedd/surveda#2118]
We're getting lots of errors in Staging: https://sentry.io/organizations/instedd/issues/3224112765/?project=105692&query=is%3Aunresolved

Thread: https://manas.slack.com/archives/C1L7CJMNU/p1656945460481729

Let's analyze what this error is about, why it's happening, if it can happen in Production as well and if it's worth fixing it.

**Comment by matiasgarciaisaia** [comment]
The issue's been lost in Sentry (it only keeps errors for 90 days), and the only info we have in Slack is that it's an issue in a Nuntium callback.

Closing until we find this again.
