### ISSUE TITLE
Callbacks don't reach ChannelBroker properly

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#2148]
This doesn't affect the majority of callbacks. Considered corner cases during development, it affects the main app flow. If we don't take action on this, the GC will be in charge of the survey progress and the ChannelBroker state won't be reliable enough.

1. Add `confirmed` state in the filter (replace `delivered`?)
2. Try to receive the channel_id in the callback to identify unequivocally its corresponding process.

**Comment by ysbaddaden** [comment]
1. We should just react to what Surveda currently reacts: `delivered` and `failed`. They're enough to progress a respondent, and shall be enough for ChannelBroker.
2. Yeah, ideally set it on each message (similar to `respondent_id`), but we could quickly add it to the provider's channel configuration (e.g. `callback_url` and `status_callback_url`) for starters.
