### ISSUE TITLE
Channel Broker bypassed in Nuntium Channel

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#2150]
Before the existence of the Channel Broker, the endpoint that receives AT messages from Nuntium ([this function](https://github.com/instedd/surveda/blob/289e36dab88b8c55153bb929375ffb8f5aca141f/lib/ask/runtime/nuntium_channel.ex#L95-L139)) answers the callback with a JSON that contains AO messages. Then those AO messages are immediately created on Nuntium.

While developing the Channel Broker, we weren't aware about this behavior. We thought `NuntiumChannel.ask` was the only function that delivered AO messages.

The main negative consequence of this bug is:

1. These AO messages aren't limited by the channel capacity (and its overloading state!). These messages should be sent to the Channel Broker with the maximum level of prioritization, and it should send them ASAP. But if the channel is overloaded they should wait until it's not.

Another negative consequence I'm observing is:

2. Every AO message sent to Nuntium will trigger an AO message status callback from Nuntium to Surveda, handled by [this function](https://github.com/instedd/surveda/blob/289e36dab88b8c55153bb929375ffb8f5aca141f/lib/ask/runtime/nuntium_channel.ex#L65-L93). The ChannelBroker will be noticed about this update and will try to clear a slot for a specific respondent. The ChannelBroker won't know for now (maybe this can be fixed in the future) to which AO message this status update is specifically related. Then, the slots it will try to clear will be more than it previously created when sending AO messages. I don't expect this to be a big problem, because this Channel Broker behavior is wrapped by respondent. This is why I expect the ChannelBroker will support having more status updates than expected without much trouble. But it wasn't for sure what was planned while developing it.

**Comment by ysbaddaden** [comment]
**Analysis**

I assume the behavior of the Nuntium channel integration is correct: we want reply messages to be sent ASAP; responding to the callback with the reply is an appropriate behavior. It avoids replying OK to Nuntium, while we push the reply to the queue (with highest priority), which will eventually call Nuntiun... but, we already got a connection from the start!

**Proposal**

We must, however, report this to the channel broker. It could forcefully increment the "queued messages" counter by +1, even allowing the counter to be greater than the channel limit.

That would prevent continuing to send contacts while replies are sent, and more importantly avoid miscalculating the actual channel load by properly counting +1 and -1 when we receive the "message sent" callback.

**Surveillance**

We might reconsider the channel behavior if we ever notice channel queues going noticeably higher than their allotted limits. We should consider an alerting system to notice that.

poke @manumoreira @matiasgarciaisaia

**Comment by matiasgarciaisaia** [comment]
For context, during real-world full-scale surveys, the effect of this change would be negligible. The response rate tends to be around 5% (I think it's never been higher than 10%), so the extra AOs generated in reply shouldn't affect the pace of the contacts _that_ much.

So I agree that just _taking the extra AOs into the channel broker accountability_ should be enough for most cases.

Adding observability should also help uncover other issues with the approach.
