### ISSUE TITLE
Garbage collector doesn't run all along

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#2158]
The GC was developed expecting it to run every X minutes (defaulted to 10) **always!**, which isn't happening.

When doesn't it run? It doesn't run when the Channel Broker isn't active.
When isn't the Channel Broker active? It isn't active after a period of inactivity.

The goal of turning the Channel Broker down after a period of inactivity was to avoid having unnecessary processes running. But while developing it we didn't realize that the GC is an internal behavior inside the Channel Broker, and then if the Channel Broker process isn't live then the GC doesn't run.

### How urgent is solving this bug?

I think not much. It isn't the expected or the desired behavior. It should be better if the GC runs every X minutes, being the Channel Broker active or not.

But the Channel Broker should work OK without the GC. It could be less stable, since if callbacks are lost nothing will prevent the ChannelBroker from being blocked by reaching its capacity with outdated contacts.

Also, some workarounds can be taken to reduce its consequences, like increasing the timeout that makes the Channel Broker terminate because of being inactive (ENV variable: `SHUT_DOWN_MINUTES`)

**Comment by ysbaddaden** [comment]
I'm really not fond of having _both_ Surveda and Verboice running a GC to cancel long pending active calls. They really ought to talk together, and Verboice is handling the calls and should be the one in charge of cleaning up.

We should really fix Verboice's GC not reporting back to Surveda that it cancelled a call.

**Comment by ysbaddaden** [comment]
Confirming that this isn't an issue. The channel-broker-gc is meant to cleanup the channel-broker activate/queued contacts for a given, active, channel. It only needs to run when its associated channel-broker process is running.
