### ISSUE TITLE
Cannot assign bucketid to answer with decimals

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2164]
Running a survey at https://surveda-africa.org/projects/12/surveys/120 the overview UI crashed due tp an answer with decimals for the Age step.
It is OK to accept answers with floats or doubles in numeric steps, so to fix should focus on allowing surveda to parse non-integer numbers and assign quota bucketid

**Comment by matiasgarciaisaia** [comment]
Bucket matching is [assuming the answer is an integer](https://github.com/instedd/surveda/blob/fbfbdd95ed2660c6d69a63e5f4a8becab85964ef/lib/ask/quota_bucket.ex#L44).

In the case that triggered the bug, the respondent answered `22.8` as age via SMS.

**Comment by matiasgarciaisaia** [comment]
Today we've seen another occurrence of this bug, with a respondent that sent their date of birth instead of age. They sent `27.12.2022`, which Surveda interpreted as `27.12` - hitting the same bug, in an uglier way.

**Comment by matiasgarciaisaia** [comment]
This was indirectly fixed by #2186 (see #2173, too).
