### ISSUE TITLE
Create an admin panel for project

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2172]
The projects control questionnaires and surveys in Surveda, so it would be helpful from the users' perspective to control some variables at the project level.
- Default timezone (this will apply to all the surveys in the project)
- Initial success rate (this is now controlled by 3 environmental variables that work at the instance level) -     We should provide 2 ways for this
      - Input initial success rate
      - Input values for the 3 variables (eligibility rate, response rate, valid respondent rate)
- Name
- Color schema is not a priority, if it's complicated we can leave it for a future version

[Mockups](https://invis.io/M4135750P9HW)

**Comment by matiasgarciaisaia** [comment]
Let's allow Admins to edit these settings, and Editors & Readers to see them read-only - if that's easy to implement.

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
