### ISSUE TITLE
Only accept integers for numeric answers

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2173]
Last year we've got some complicated answers on SMS mode.
[See thread](https://manas.slack.com/archives/C3KKQKHLG/p1667407241518149)
We realized that (for some reason) we are accepting non-integer answers for numeric steps. We are parsing the answers to make them "valid" and this is generating more problems than benefits.
We should only accept integers for numeric steps.

**Comment by matiasgarciaisaia** [comment]
See #2164

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
