### ISSUE TITLE
Validate audio files in questionnaire editor

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2175]
Currently the quex editor accepts any file with mp3 or wav extension. There's no validation of the file format
The wav to mp3 conversion works but without validation we usually endup having multiple issues with audio files. 
Steps:
1. Validate if the uploaded files are OK
2. Convert to mp3 if wav
3. Validate if conversion to mp3 was successful

**Comment by sardar-usman** [comment]
@ysbaddaden It working fine for `Wav` and `pm3` format files.
