### ISSUE TITLE
Fix survey retries histogram tooltip

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2176]
Currently, in the retries histogram the tooltip with the value label of each bar isn't showing properly
<img width="745" alt="Screenshot 2023-02-06 at 18 55 34" src="https://user-images.githubusercontent.com/31930782/217096886-bd34550c-88ac-4a89-9853-8b0f4da2cd10.png">

**Comment by matiasgarciaisaia** [comment]
See #1631
See https://manas.slack.com/archives/C1L7CJMNU/p1670947760143369

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
