### ISSUE TITLE
Create a success rate chart

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2177]
A year ago we decided to include the success rate date into the main overview line chart.
Back then It was an acceptable quick solution, but then we realized that it had a negative effect on the chart.\
As it is a forecast chart (forecasts target completion) it tries to forecast success rate completion and dramatically modifies the x-axis range.
We should have a separate chart to track the daily success rate

**Comment by manumoreira** [comment]
@jkicillof would you be able to sketch a small chart for the daily success rate in the survey overview?

**Comment by jkicillof** [comment]
Let me know if [this](https://projects.invisionapp.com/d/main#/console/8374235/266351230/preview) works

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
