### ISSUE TITLE
Troubleshoot Local_Gateway_Simulator to make it work locally

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2193]
We need to simulate a volume of survey answers (~200 completes) to work on #2178 and #2177
Unfortunately, https://github.com/instedd/ncd_local_gateway_simulator didn't work locally on the first attempt.

**Comment by manumoreira** [comment]
Timebox this issue to a few days and focus on making it work locally (try to avoid huge refactors)

**Comment by leandroradusky** [comment]
Please see [this PR](https://github.com/instedd/ncd_local_gateway_simulator/pull/1), and when is merged this issue is ready to be closed.

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine now.
