### ISSUE TITLE
Show running surveys count in surveys folders

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#2196]
Surveda's Projects screen show every project with the amount of currently running surveys.

<img width="1139" alt="Screenshot 2023-03-03 at 12 12 48" src="https://user-images.githubusercontent.com/5470539/222757214-d07eb4c1-c05e-45d5-96ab-7a7cd0b51521.png">

Before introducing survey folders, when the user selected a project, the Surveys index would quickly show which surveys were running - since they stay at the top.

But now there's a chance that the running surveys are inside a folder, so the user gets into a project thinking "there are 2 running surveys", but then get into the project - and have no clue where those two running surveys are.

<img width="1139" alt="Screenshot 2023-03-03 at 12 12 57" src="https://user-images.githubusercontent.com/5470539/222757225-e442fce3-b6bb-4962-9f47-4cda18823efa.png">

It'd be nice to display a counter in each folder, stating how many active surveys there are.

Something in this spirit - but that doesn't hurt anybody's eyes.

<img width="1139" alt="Screenshot 2023-03-03 at 12 12 57" src="https://user-images.githubusercontent.com/5470539/222759358-015925cc-2c55-4c57-8dbf-0ccdf5ae156d.png">

**Comment by ysbaddaden** [comment]
@manumoreira Maybe we'd like some design?

**Comment by manumoreira** [comment]
@jkicillof we need your help here.
We can either do what @matiasgarciaisaia suggests (adding a notification circle with a number) or change the folder view to show more information (total survey, active surveys, archived, etc.).
Keep in mind that shoulders share the view with surveys and look like this 
![folders surveys](https://user-images.githubusercontent.com/31930782/226421350-3e5991a7-05ba-4080-94ba-135cda5df8ce.png)

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/180693793/preview

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
