### ISSUE TITLE
`docker build` should be enough 

### ISSUE THREAD

**Issue by anaPerezGhiglia** [instedd/surveda#2197]
Currently, we are building the image by a combination of `build.sh` [script](https://github.com/instedd/surveda/blob/fbfbdd95ed2660c6d69a63e5f4a8becab85964ef/build.sh#L15-L17) (that downloads and publish ui dependencies) and `Dockerfile`

The dockerfile should take care of building the ui and then copying that into the right directory

**Comment by ysbaddaden** [comment]
Multi-stage builds to the rescue :)

**Comment by diegoliberman** [comment]
Will be implemented in #2223
