### ISSUE TITLE
Line chart not working on survey card

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2199]
Currently, the line chart in the survey card is not working.

<img width="1321" alt="Screenshot 2023-03-06 at 10 53 05" src="https://user-images.githubusercontent.com/31930782/223130699-4fffa901-103e-42dc-813a-ea46025afda0.png">

This might be probably related to #2054

**Comment by ysbaddaden** [comment]
FWIW: the line chart is fixed on my local for panel surveys and surveys:

![Capture d’écran de 2023-04-14 15-19-09@2x](https://user-images.githubusercontent.com/47380/232054813-48803cce-af6d-401c-9939-33b71931bd79.png)

![Capture d’écran de 2023-04-14 15-19-56@2x](https://user-images.githubusercontent.com/47380/232054980-6cce1bbe-1fb3-49a1-b0f2-96f98d50cc75.png)

I think it's safe to push to production along with 0.36.1.
