### ISSUE TITLE
Add batch_limit_per_minute on admin console

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2206]
`batch_limit_per_minute` currently is an environment variable that operates at the instance level to control the amount of max number of respondents that are set to active in the surveys.
We should add it to the project admin console as we did with `eligibility_rate`, `response_rate`, etc
![adminPanelLimitPerMinute](https://user-images.githubusercontent.com/31930782/224571816-eb268e1a-1dd7-4a97-856d-869731b9dafb.png)

**Comment by leandroradusky** [comment]
Two things here, just to be all on the same page:

1) In the config there are two vars:

```
  batch_size: {:system, "BROKER_BATCH_SIZE", 10000},
  batch_limit_per_minute: {:system, "BROKER_BATCH_LIMIT_PER_MINUTE", 100},
```

Will the `batch_size` be as well a project setting? If yes, maybe this is the moment to implement it.

2) This setting is used by the Broker in two methods: `retry_respondents(now)` & `start_some(survey, count)`: 

While in the second we have the survey to get the project from (which will have this setting), the first one is a method performed at the `Broker` level: there is no survey involved at `retry_respondents`, just respondents no matter which survey they are coming from. Then, a decision needs to be taken here (i.e.: go respondent by respondent to its survey, then to its project, then to the setting and don't surpass the batch limit grouping respondents by its project? something else?)

cc @manumoreira @ysbaddaden

**Comment by ysbaddaden** [comment]
Hum, respondents belong to a survey, so we may first list surveys with respondents to recontact, then iterate that list to contact respondents, only accessing the survey's project once per survey?

**Comment by manumoreira** [comment]
Thanks for bringing this to my attention.
I expected this discussion to start in #2172 as it was the first time we wanted to apply environmental variables at the project level. 
There are two ways to get a `batch_size` one is to use the default value from the variable and the other is to calculate it from the `initial_success_rate` and the target (Target/ISR = batch_size)
I have two comments moving forward:

1. How is this working now for #2172 ?
2. We might want to add `batch_size` to the admin panel but first we should rename it to `default_batch_size` to prevent misunderstandings.

**Comment by leandroradusky** [comment]
I copypaste here the values in my local configuration (not sure these are values consistent with the production servers):

```
config :ask, Ask.Runtime.Broker,
  batch_size: {:system, "BROKER_BATCH_SIZE", 10000},
  batch_limit_per_minute: {:system, "BROKER_BATCH_LIMIT_PER_MINUTE", 100},
  ...
```

In the `Broker` the `batch_size` is used as follows

```
  # Estimates the amount of respondents the broker will have to initiate contact with
  # to get the completed respondents needed.
  defp batch_size(survey, respondents_by_state) do
    case Survey.completed_respondents_needed_by(survey) do

      :all ->                                        ### <- IF WE NEED ALL
        default_batch_size()                         ### <- USE ENV PARAMETER

      respondents_target when is_integer(respondents_target) ->              ### <- "ELSE"

        successful = Survey.completed_state_respondents(survey, respondents_by_state)
        estimated_success_rate = estimated_success_rate(survey, respondents_target)

        ((respondents_target - successful) / estimated_success_rate)         ### <- USE THIS FORMULA
        |> trunc
    end
  end
```

So, then, is basically the very same that you are mentioning what is being done now; but using the environment variable instead of a project-specific one. If we add the project variable is just to load it from the project when calling `default_batch_size()`.

**Comment by sardar-usman** [comment]
@leandroradusky It is working fine.
