### ISSUE TITLE
Regular check call/message state (to fix desynchronizations)

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2252]
**Context**

I got the channel broker to be completely desynchronized from Verboice's queue. Surveda thought that the queue was filled, while the queue in Verboice got emptied. There may be various reasons, possibly non standard, but if they can happen in development, they may happen in production, and a survey going to a halt because of the channel broker is _very_ bad.

The active call GC won't help. It's meant to handle a few calls in desync, that won't affect the channel much, but here we're talking about a full desync (100 active vs 0 in reality) hanging up the whole channel :fearful:

**Proposal**

I'm proposing to implement a regular check of the real status of active contacts (calls/messages) to verify that the state in Surveda is still correct:

- yes: the active contact is really active/queued in the actual channel (allright);
- no: the active contact is no longer active/queued in the actual channel (oops, deactivate the contact).

Maybe we don't need to check _all_ active contacts, but those that have been pushed to the channel for some time (e.g. over 5 or 10 minutes, configurable). Hopefully, and after some fine tuning (channel capacity, active lifetime), it might never be called, except to fix a situation gone wrong.

We could also report when we fix a desync, reporting which calls needed to be corrected, so we could investigate from logs.

**Notes**

Once implemented, we can probably drop the active call GC for the Channel Broker. We can let the equivalent active call GC in Verboice stop calls when they take too long (likely the result of a bug), that will notify Surveda _or_ Surveda will find out during the next state check (at worst).

**Verboice** has an API endpoint to check the actual state of a call `/api/calls/:call_id/state`. We could enhance it to support reporting the state of multiple calls at once (to group http requests).

**Nuntium** doesn't have an API endpoint to check the state of AO messages, but we could add it. Same it could support checking multiple AO messages at once.

Both Verboice and Nuntium are old Ruby on Rails applications. It shouldn't be hard to enhance / add these endpoints.

TODO:
- [x] CHNLBRK: save the `call_id` in channel broker when making an IVR call to Verboice;
- [x] CHNLBRK: save the AO message token (`x-nuntium-token`) in channel broker when sending SMS messages to Nuntium;
- [ ] Verboice: add or modify endpoint to get the state of multiple calls at once (optional);
- [x] Nuntium: add an endpoint to get the state of one (and/or multiple) AO message(s);
- [x] CHNLBRK: configuration to tell how often we must verify the active contacts, and how long a contact can stay idle;
- [x] CHNLBRK: new process to regularly check the state of "active contacts" that have been idle for too long:
  - [x] Verboice: check the state of the call;
  - [x] Nuntium: check the state of the set messages;
    - [x] Bug: check the state for _each_ message in the set (and unlock all slots at once);
- [x] Verboice progress callback: notify channel broker of in-progress (to touch the last updated time);
- [x] CHNLBRK: ~~drop the active call GC~~ revamp the GC to check for idle time.
- [x] Tests:
  - [x] Verboice
  - [x] Nuntium

Where to set the envvar? project settings? channel settings?

**Comment by ysbaddaden** [comment]
I suppose we could do the same in Verboice: ask the external provider for the actual state of long active calls :thinking:

**Comment by diegoliberman** [comment]
I would start with the setting at the Channel level.  
The idea about Verboice monitoring against external providers, sounds good, but afterwards and probably not during this project phase.

**Comment by ysbaddaden** [comment]
Looking into `Ask.Runtime.VerboiceChannel` we already record the `call_id` (as `verboice_call_id`). We use it in two cases: verify whether we already queued a call and to cancel a call. In fact `Verboice.Client.call_state/1` is even already available :rocket:

**Comment by matiasgarciaisaia** [comment]
I like the idea. I think it's correct to frame this as an extension to the active calls GC.

Reporting desyncs would be really nice, to help us understand the root cause.

I wouldn't bother in implementing the multiple-call check in Verboice (looks like an optimisation, and we're too early for that; plus the list of calls to check can get really long, making it a slow API call), but I guess I'd do it for Nuntium, since a single respondent can have multiple pending SMSs.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia Yeah, I didn't mean to implement this _now_ in Verboice, but it might do the same, independently. The point is to act as russian dolls:

- Verboice asks Twilio for the real state of long idle calls (+ implements the call status callback), and updates its own internal state;
- Surveda asks Verboice for the state of long idle calls (verboice replies with the state it knows, and doesn't ask Twilio on behalf of Surveda).

When Verboice notices an active call is no longer active, it shall cancel the call, which should callback to surveda, and at worst Surveda would eventually ask Verboice a little later, and notice that the state changed, cancel the call, and push another one.

Same for Nuntium.
