### ISSUE TITLE
mp4 files aren't accepted

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2269]
I tried uploading an mp4 file
https://github.com/instedd/surveda/assets/31930782/830806ab-2176-42d2-bef8-f91a15e23531

and it throws an error 
![image](https://github.com/instedd/surveda/assets/31930782/66621d67-f629-4ea4-b4c1-2737444d7b9b)

it also shows an incorrect warning
![Screenshot 2023-05-10 at 13 34 02](https://github.com/instedd/surveda/assets/31930782/23f8f1f5-f260-445e-b029-636fdb0160f6)

Tested on Chrome Version 113.0.5672.63 (Official Build) (arm64)

**Comment by ysbaddaden** [comment]
I reproduced on staging. The problem is in the browser's JavaScript: it uploads the file with a content of `undefined` which is obviously an invalid audio file.

```
-----------------------------33682635730838583681053804666
Content-Disposition: form-data; name="file"

undefined
-----------------------------33682635730838583681053804666--
```

**Comment by ysbaddaden** [comment]
Cornering the issue: there are no problem when uploading .AAC, .M4A, .MP3 or .WAV files. Only when selecting a .MP4 file.

**Comment by sardar-usman** [comment]
@ysbaddaden It uploads the mp4 files audio with this error.
<img width="1719" alt="Screenshot 2023-05-22 at 10 06 57 PM" src="https://github.com/instedd/surveda/assets/45853972/7e914e99-93e9-4000-ae0b-275487f5b8e8">

**Comment by sardar-usman** [comment]
@ysbaddaden It is working as expected.
