### ISSUE TITLE
Channel Broker: re-enqueue :low contacts as per the respondent's disposition

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2289]
The reasoning for the `:low` level was to avoid to dequeue just to reenqueue the contact because `not_before` isn't reached, which would impact performance if we have another survey using the the channel (on different schedules).

But when the survey is resumed on the following day, it'll push new contacts as `:normal` and they'd take precedence over the `:low` messages, whatever the respondent's disposition. Hum :thinking:

The channel-broker-gc now runs often (every 2 minutes by default) and it queues contacts 10 minutes before `not_before`, so contacts should get queued before the survey-broker starts pushing new contacts if the channel isn't used by another survey, but if the channel is used by another survey, they'll stay in `:low`. Damn.

Maybe we could add a pass to the channel-broker-gc to dequeue/re-enqueue messages as per the respondent's disposition when `not_before` is reachable?

**Comment by ysbaddaden** [comment]
If #2297 gets merged, we might not need to have a `:low` priority queue anymore: the channel-broker won't try to dequeue contacts until they're about to be contacted.

**Comment by manumoreira** [comment]
#2297 was finally merged, can you confirm that we don't need to have the `:low` priority queue anymore?

**Comment by ysbaddaden** [comment]
From a quick glance, I would say we don't need it anymore. That should still be verified, though.

**Comment by manumoreira** [comment]
After a few smoke tests on stg we didn't see any major issue with the ChBrk, it looks like its enough to treat this as verified, but I'd prefer to get someone else confirmation. 
@anaPerezGhiglia @matiasgarciaisaia can you confirm?
