### ISSUE TITLE
Review the Channel Broker

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2292]
See https://github.com/instedd/surveda/wiki/How-to-test-channel-related-issues for details.

I'd suggest to first try quick & small surveys, with a single mode/channel, 100 respondents, and low limits/capacities to get the hang of it, and see if you find simple issues.

Then go on to a larger scale survey (over 10000), multiple modes/channels, and eventually multiple surveys, schedules, and so on. (edited) 

Then a final test with a couple surveys with 100000 respondents, primary/fallback channels, consequent batch/channel limits & capacities, ... low reply rates, long answers in the simulators, and so on.

Let's see what realistic values that we can expect from real surveys.

**Comment by ysbaddaden** [comment]
> Usually surveys have a success rate between 1 and 5%. Meaning 1 to 5 completes/partials for every 100 respondents. They usually have a target between 2000 and 5000 completes/partial. Using a 100000 respondents sample looks reasonable.
>
> An IVR channel with low capacity can send 10K call attempts every 12 hs ~13 calls per minute, I’d say that limiting the channel broker to 10 calls sounds reasonable.
>
> An SMS channel with low capacity can send 30k MT SMS evert 12hs ~40 per minute. Maybe limiting the channel broker to 30 sms is OK, but we can limit it a bit more if needed for testing purposes

**Comment by sardar-usman** [comment]
@ysbaddaden It is working fine.

**Comment by ysbaddaden** [comment]
@sardar-usman did... you... run many tests as proposed in the issue? they passed :exploding_head: ?

**Comment by sardar-usman** [comment]
Yes, I have tried with 100 and 1000 respondents respectively.

**Comment by ysbaddaden** [comment]
Additional tests were conducted by @manumoreira and @matiasgarciaisaia:
https://manas.slack.com/files/T02JWDRK4/F05FW2AQC94
