### ISSUE TITLE
ChannelBroker: add a new case to prioritize contact attempts

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#2306]
## The new case
Currently, we prioritize the contact attempts of the respondents with `disposition != queued`.
This is enough for SMS but not for IVR,  to fully guarantee the retry window we should add another case based on the number of previous attempts. If previous attempts > 0 then it should be prioritized.

## Things to consider
~This might affect the size of the prioritized contact attempts queue in the channel broker impacting negatively in other respondents that should have a higher priority (like the SMS respondents that have just replied to a question), let's keeo an eye on this when testing.~

**Comment by ysbaddaden** [comment]
No worries: SMS replies are sent immediately in response to the callback, regardless of the current capacity of the channel (they can be sent in excess). They're still counted so we won't push more high/low priority contacts. See #2150
