### ISSUE TITLE
[Survey] Autosave should work without leaving the field

### ISSUE THREAD

**Issue by juanboca** [instedd/surveda#280]
When the user presses enter/return the focus should be removed from the field, all the validations performed, and the value should be saved.

**Comment by nditada** [comment]
@mmuller Can you verify this and close it or assign it to 0.24?

**Comment by mmuller** [comment]
This issue is still present in version be9eb68

**Comment by bcardiff** [comment]
It's not about the enter and running validation, but:

* the autosave should work even if focus is not lost
* triggering validation errors should not prevent user to keep typing really slow
* no keystrokes shuold be lost if validation from the server arrives after a new keystroke
* should advertise that not all the changes are saved
* this apply to all fields

**Comment by mmuller** [comment]
Working properly in version 1984618
@bcardiff should we create an issue to fix it in the whole application?

**Comment by bcardiff** [comment]
Sure @mmuller. Note that as long as the feature is working, then it is more a tech-debt. The other missing thing we discussed was about the visual cue of saving not always visible.
