### ISSUE TITLE
[Survey] Replace Timezone select with search textbox

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#297]
There are almost 600 timezone options. The control is unusable because you can't type to look for your timezone directly.

<img width="404" alt="screen shot 2016-11-14 at 15 46 44" src="https://cloud.githubusercontent.com/assets/651693/20277982/b7068620-aa81-11e6-937f-9cc76e3f8c27.png">

**Comment by bcardiff** [comment]
Use the same component for assigning projects to channel or language selection.

**Comment by mmuller** [comment]
It is not working properly in version 8654e87
When entering a blank space after the first word the dropdown is hidden.

https://recordit.co/HUFKQNQmN3

**Comment by mmuller** [comment]
Working properly in version e4f1cad
