### ISSUE TITLE
Optimize quota checking for respondent responses

### ISSUE THREAD

**Issue by asterite** [instedd/surveda#352]
Right now after each respondent response the session checks if the respondent falls in a quota already completed, as per #336. However, this check could only be needed to do if the current response is inside `session.quota_vars`. This will result in less DB queries executed.

However, this also changes the behaviour. Right now if another respondent fills a quota bucket, then on a next response of a current user there is a chance to hang up the call. With the optimization applied the call will continue. So, this should be discussed before being implemented.

**Comment by nditada** [comment]
@waj Can you please decide on this one and close it or move it to 0.24?

**Comment by waj** [comment]
The code changed since this issue. The process could be improved but is not as bad as it was before.
