### ISSUE TITLE
Curate list of languages for language autocomplete

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#356]
The current list contains some non-sensical items and lots of unnecessary duplicates.

**Comment by nditada** [comment]
We need to find a better curated list.

<img width="286" alt="Screen Shot 2019-09-17 at 12 35 46 PM" src="https://user-images.githubusercontent.com/1359189/65056691-b428f800-d947-11e9-9b52-5d15eaa232d7.png">

**Comment by manumoreira** [comment]
If we filter by living in Language_Type and not blank in Part2B it generates a reasonable list of languages.
https://docs.google.com/spreadsheets/d/1CmoViP1SCiAZ9HtZQjUn8kj0bq2KIw-bAFf4cyLOMQg/edit?usp=sharing

**Comment by waj** [comment]
Part2T is the code that matches the iso-639-3. We're using this library: https://github.com/wooorm/iso-639-3

Let's filter by: `type == "living" && iso6392T != null`

**Comment by mmuller** [comment]
Working properly in version d7ff690
