### ISSUE TITLE
[Respondents] Values other than numbers or dates should be left-aligned in tables

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#409]
Version: 0.4.0-dev-c76692f (build 1011)

At the moment all values are left aligned. **Numbers and dates** should be right aligned.

![screen shot 2016-12-07 at 2 26 20 pm](https://cloud.githubusercontent.com/assets/9214460/20978839/325edf7a-bc89-11e6-9361-758fd609b1b8.png)

**Comment by Mscebba** [comment]
There should be a class for number and dates to align them in css

**Comment by mmuller** [comment]
Working properly in version b91c95c
