### ISSUE TITLE
Question - Cutoffs, Sample, and Bias of Fast Responders

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#433]
Something survey methodologists wish to control for is bias among those who respond faster than others (e.g., young people vs. old people) 

Here is a question... 
What if Ask sends out a bunch of invites, then 500 is reached for a cutoff, and then someone from the batch of invites responds? We DO want that person to be allowed to complete the interview. Otherwise, we are giving the advantage to people who are fast responders. In other words, we want the cutoff rules to govern the Ask INVITATIONS but not necessarily the acceptance of an interview.

**Comment by nditada** [comment]
If we want to allow people that respond "later" to make it to the sample, then what would be the meaning of a "completed cases" cutoff? 

In other words, there are two mutually exclusive options:
- The system stops accepting cases when 500 respondents complete the quiz
- The system accepts responses from people that respond AFTER  the 500 results are completed.

The only somewhat reasonable mashup of both requirements would be to have a late response to replace or "push-out" a random earlier response... but I find that extremely cumbersome.

**Comment by steesdale** [comment]
Todo: Please add to backlog of issues to discuss during upcoming planning sessions.

**Comment by steesdale** [comment]
@nditada did we come to a resolution on this already?  If so I can close this one.
