### ISSUE TITLE
Use the last contact attempt wait time as the timeout to mark a respondent as stalled

### ISSUE THREAD

**Issue by nditada** [instedd/surveda#452]
For example, if the re-contact attempt schedule is 1d 1d 2d,  then the time to wait before marking the case as failed would be 2 days

**Comment by nditada** [comment]
For now let's keep the hardcoded 10 minutes

**Comment by manumoreira** [comment]
@nditada do we still want this?

**Comment by manumoreira** [comment]
After #1526 this issue became important again. for two reasons.
1) The histogram makes the timeout evident
2) The hardcoded 10 minutes are hard to draw in the chart ( as any time range < 1 hour)
Currently in surveys in which the fallback delay is defined this value is used as timeout to make the respondent failed.
The simplest solution would be changing the hardcoded time to 1 hour and use the last contact attempt wait time as the timeout to mark a respondent as failed

**Comment by mmuller** [comment]
Working properly in version 672562a
