### ISSUE TITLE
[Channels] Show which account is being authenticated with Ask in popup window

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#466]
Version: 0.5.0-dev-6b4a50c (build 1092)

Display the user account being associated with Ask for both Nuntium and Verboice

![screen shot 2016-12-23 at 2 56 59 pm 1](https://cloud.githubusercontent.com/assets/9214460/21459775/1c299486-c920-11e6-8b19-89be7614432a.png)

**Comment by manumoreira** [comment]
Currently, we are showing the instances(verboice or nuntium servers) from which we are using the channels
