### ISSUE TITLE
[Data Download] [Respondents UI] Date Field w/o timezone

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#528]
Currently when you download the results, the date field has a day-time format.  It is unclear what timezone the data is presented in.  

Suggestion: 
- Have the column header include the timezone - or something like this. 

<img width="653" alt="screen shot 2017-01-11 at 11 50 21 am" src="https://cloud.githubusercontent.com/assets/3987608/21859946/3b7e4916-d7f4-11e6-8a89-aae11c1421d1.png">

**Comment by mmuller** [comment]
I could reproduce this issue in version ee7b498

Preconditions:
There is a Survey finished.

Reproduce steps:
Navigate to the Respondents tab.
Press 'Download results'.
Open the file and observe the data under 'Date'.

Obtained:
The Date column doesn't include timezone.

Screenshot:
<img width="494" alt="screen shot 2017-02-15 at 4 03 48 pm" src="https://cloud.githubusercontent.com/assets/518152/22990676/ba5941f4-f398-11e6-9aae-0ff9a6db1a28.png">

**Comment by steesdale** [comment]
I would note that this presents the same way on the respondent page as well.   

It would be a "nice to have" it stating the time zone selected by the user in  the UI: 

![screen shot 2017-02-16 at 11 01 12 am](https://cloud.githubusercontent.com/assets/3987608/23031717/90503684-f437-11e6-98ae-5117bd2fa97d.png)

**Comment by manumoreira** [comment]
The timezone for all the date fields is the one defined for the survey 
<img width="734" alt="Screen Shot 2019-11-15 at 15 21 47" src="https://user-images.githubusercontent.com/31930782/68965914-b11d7d00-07bb-11ea-8cea-bd0f69b07622.png">
