### ISSUE TITLE
[Copywriting] Is "taking the pulse of the people" appropriate?

### ISSUE THREAD

**Issue by mverzilli** [instedd/surveda#535]
(See "Collect opinions" in the landing page). It sounds a bit creepy to me, but maybe it's ok for a native speaker.

<img width="630" alt="screen shot 2017-01-12 at 11 02 47 am" src="https://cloud.githubusercontent.com/assets/651693/21892714/de8ac432-d8b6-11e6-8bdc-e945afcbc852.png">

**Comment by manumoreira** [comment]
It sounds quite creepy to me too, but it seems widely used in native speakers when referring to polls or surveys
https://www.nytimes.com/2006/10/15/style/15iht-design16.3160786.html
https://www.everydaysociologyblog.com/2016/05/polling-methods.html
https://www.spiralq.org/education/sparq-in-schools-west-taking-the-pulse-of-the-people-at-our-partner-schools/
