### ISSUE TITLE
There are variable names stored with spaces.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#561]
We should run a migration in order to remove them.

Related to #470

**Comment by mverzilli** [comment]
Would you provide reproduction steps so we have a baseline to check against?

**Comment by mmuller** [comment]
@mverzilli, this issue is related to #470 because the variable name autocomplete shows duplicate variables in version 0.5.0-dev-38873bb (build 1384).

The reproduction steps are:
Go to create a Questionnaire
Add a Step
Click on Variable Name field
Fill the field with `Ge`

Obtained:
The text `Gender` is displayed twice.

**Comment by waj** [comment]
This is now irrelevant. Let's fix specific cases if needed without a migration.
