### ISSUE TITLE
Issue when re-contact attempts are 1m

### ISSUE THREAD

**Issue by edjez** [instedd/surveda#570]
@waj said I should log this, so I must.

**Comment by manumoreira** [comment]
We will validate that the minimum time window is 10m

**Comment by bcardiff** [comment]
Add client-side validation to ensure attempts are at least every 10m.

**Comment by aeatencio** [comment]
`0m` `0h` and `0d` values aren't being validated either

![0m 0h and 0d](https://user-images.githubusercontent.com/39921597/94017816-3ed7da80-fd86-11ea-9bc7-1b4a09805c45.png)

**Comment by mmuller** [comment]
Working properly in version da07ac7
