### ISSUE TITLE
[Survey] Add text-align center to percentage row in Comparisons survey step

### ISSUE THREAD

**Issue by pmallol** [instedd/surveda#644]
Version: 0.6.0-dev-d445c84 (build 1566)

![screen shot 2017-02-10 at 3 12 27 pm](https://cloud.githubusercontent.com/assets/9214460/22838347/7c88d004-efa3-11e6-9f71-8cace30113bf.png)

**Comment by mmuller** [comment]
Working properly in version 672562a
