### ISSUE TITLE
Invite 2nd User to project when They are Not Already Logged In

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#659]
What Happened: 
- I invited a 2nd user to a project I created 
- The 2nd user was not logged into the tool 
- The 2nd user saw the email invitation and clicked on the link
- The 2nd user is directed to the log-in screen and logs in
- The 2nd user see's no invite and no existing projects/ 

What I expected
- That the 2nd user, after they logged in, would see the invite or the project already in the list of current projects. 

Note: If I was already logged in, the invite shows up normal when clicking through from the email invitation link.

**Comment by aeatencio** [comment]
Since #782 shared projects are shown without the invited user acceptance. Thanks, @mmuller!
