### ISSUE TITLE
[Survey] Multiple Sample File Upload

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#664]
What Happened: 
- You load a sample file
- A second location to load a sample file appears
- I found it confusing why this box duplicated

What I expected: 
- I expected to load a first file
- Then to have some sort of button or expand button or something like it, that introduced me to the idea that I could have an additional sample file.   Expanded as needed -> many users wont need the 2nd sample file.

**Comment by mmuller** [comment]
Version ee7b498.

Screenshot:
<img width="1374" alt="screen shot 2017-02-17 at 9 55 15 am" src="https://cloud.githubusercontent.com/assets/518152/23066046/502b6130-f4f7-11e6-806b-8318dec86c9c.png">
