### ISSUE TITLE
Ask confirmation before changing the Step type.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#732]
Found in version 02bcf64.

Preconditions:
There is a Numeric Step 'Foo' with the fields already filled. 

Steps:
Go to edit the Step 'Foo'.
Select 'Explanation' from the Step types.
Select 'Numeric' from the Step types.

Obtained:
The information is lost.

Expected:
When changing the Step type it would be helpful to ask confirmation before submitting the action.
Besides that we can show some message like: "The form will be cleared. Do yo want to confirm the action?"

**Comment by waj** [comment]
I'd like to see an "undo" feature instead of asking for confirmation of destructive actions

**Comment by manumoreira** [comment]
This is working properly at version [63fd132](https://github.com/instedd/surveda/commit/63fd132713b5486d588c63840754e951d214758d)
