### ISSUE TITLE
[Channels] It would be helpful to display metadata/config of channels

### ISSUE THREAD

**Issue by steesdale** [instedd/surveda#810]
Each channel has some specific details that would be important to a survey manager during setup.  This include the expected format of the sample file (country code included or not?), max number of simultaneous calls, phone number, inbound/outbound, maybe others details. 

Currently this is obscured from a user, leading to simple errors in survey setup.  It also creates an unnecessary or unknown hurdle, where a survey manager needs to get these details from whoever set up the channel -> typically a developer.

Suggest as an enhancement, but would recommend as something to roadmap to improve user experience.

**Comment by manumoreira** [comment]
The channel owner should define the necessary patterns to make the channel work properly with different respondents files format
